### ISSUE TITLE
v1.0.0-alpha 无法获取到实体

### ISSUE THREAD

**Issue by XiangWei-Meng** [banto6/haier#100]
**问题描述**
小程序抓包获取到 accessToken 了，JSON 能看到设备 list，HA 提交 accessToken 后提示没有设备或实体

**环境信息:**
 - Homeassistant版本: [e.g. 2024.4.4]

**设备信息**
{
        "baseInfo" : {
          "parentsDeviceId" : null,
          "deviceGroupId" : null,
          "wifiType" : "00000000000000008080000000041410",
          "deviceNetType" : "device",
          "subDeviceIds" : null,
          "permission" : {
            "auth" : {
              "control" : true,
              "set" : false,
              "view" : true
            },
            "authType" : "home"
          },
          "deviceGroupType" : null,
          "deviceId" : "AC8226873054",
          "deviceType" : "03001001",
          "familyId" : "  ",
          "ownerId" : "  ",
          "deviceName" : "一卧挂式空调",
          "isOnline" : true,
          "deviceRole" : null,
          "deviceRoleType" : null,
          "devName" : "一卧挂式空调",
          "bindTime" : "2023-07-03 08:21:00",
          "ownerInfo" : {
            "ucUserId" : "  ",
            "mobile" : "  ",
            "isVirtualUser" : "false",
            "name" : " ",
            "userId" : " ",
            "avatarUrl" : "https://accountstatic.haier.com/202404302156/8325c2a8bc2ba027031aebe9938a9ec0/avatar/b1120a5ef93ed15e792e557124139a12.jpg"
          }
        },
        "extendedInfo" : {
          "appletProxAuth" : 0,
          "prodNo" : "AAABT4B02",
          "devFloorOrderId" : "1",
          "comunicationMode" : "WIFI",
          "devFloorId" : "100000000000000104",
          "categoryGrouping" : "空调",
          "brand" : "海尔",
          "imageAddr1" : "https://file.c.haier.net/obs-cpzx/materialprod/2023/12/06/1732306658651328512/e12a303318ac45537314944727dc9977.png",
          "imageAddr2" : "https://file.c.haier.net/obs-cpzx/materialprod/2023/12/06/1732306658651328512/e12a303318ac45537314944727dc9977.png",
          "detailsUrl" : null,
          "apptypeIcon" : "https://resource.haigeek.com:443/download/resource/selfService/hardware/modeltypeimg/6e127a0ab6624c95adee706710a13547.png",
          "roomId" : "832271029855000000",
          "twoGroupingName" : "",
          "configType" : "0",
          "devFloorName" : "一层",
          "apptypeName" : "挂式空调",
          "model" : "KFR-26G/MCA83U1室内机总成",
          "room" : "客厅",
          "accessType" : "13",
          "barcode" : "",
          "apptypeCode" : "A177",
          "bindType" : "SoftAP",
          "noKeepAlive" : 0
        }
      },
      {
        "baseInfo" : {
          "parentsDeviceId" : null,
          "deviceGroupId" : null,
          "wifiType" : "2008610800820324031200118006114500000000000000000000000000000040",
          "deviceNetType" : "device",
          "subDeviceIds" : null,
          "permission" : {
            "auth" : {
              "control" : true,
              "set" : false,
              "view" : true
            },
            "authType" : "home"
          },
          "deviceGroupType" : null,
          "deviceId" : "AC822646FE8C",
          "deviceType" : "0301200L",
          "familyId" : "  ",
          "ownerId" : "  ",
          "deviceName" : "客厅立式空调",
          "isOnline" : true,
          "deviceRole" : null,
          "deviceRoleType" : null,
          "devName" : "客厅立式空调",
          "bindTime" : "2023-07-03 08:17:35",
          "ownerInfo" : {
            "ucUserId" : " ",
            "mobile" : " ",
            "isVirtualUser" : "false",
            "name" : " ",
            "userId" : "  ",
            "avatarUrl" : "https://accountstatic.haier.com/202404302156/8325c2a8bc2ba027031aebe9938a9ec0/avatar/b1120a5ef93ed15e792e557124139a12.jpg"
          }
        },
        "extendedInfo" : {
          "appletProxAuth" : 0,
          "prodNo" : "AB92B0000",
          "devFloorOrderId" : "1",
          "comunicationMode" : "WIFI",
          "devFloorId" : "100000000000000104",
          "categoryGrouping" : "空调",
          "brand" : "海尔",
          "imageAddr1" : "https://file.c.haier.net/obs-cpzx/materialprod/2023/12/06/1732276170557542400/62089cf27d086de40f3bbf47cedfd11e.png",
          "imageAddr2" : "https://file.c.haier.net/obs-cpzx/materialprod/2023/12/06/1732276170557542400/62089cf27d086de40f3bbf47cedfd11e.png",
          "detailsUrl" : "https://resource.haigeek.com/ossdownload/resource/selfService/devicecustomui/wxdetailsVersionResource/index/airCondition_wx_20240416163310421/airCondition_wx/index.html",
          "apptypeIcon" : "https://resource.haigeek.com:443/download/resource/selfService/hardware/modeltypeimg/27e8f639e3c548d4b33d87f898a39998.png",
          "roomId" : "832271029855000000",
          "twoGroupingName" : "",
          "configType" : "0",
          "devFloorName" : "一层",
          "apptypeName" : "立式空调",
          "model" : "KFR-50L/KCA83U1室内机总成",
          "room" : "客厅",
          "accessType" : "13",
          "barcode" : "",
          "apptypeCode" : "A178",
          "bindType" : "SoftAP",
          "noKeepAlive" : 0
        }
      }

**Comment by banto6** [comment]
看看集成的日志

**Comment by yydlh** [comment]
抓包后，怎么获取accessToken啊，谢谢。

**Comment by yydlh** [comment]
苹果下载stream

**Comment by hsy5571615** [comment]
> 苹果下载stream

可惜没有苹果手机，我去找找安卓能用的

**Comment by banto6** [comment]
@XiangWei-Meng  参考 https://github.com/banto6/haier/issues/102 ，应该是一个问题
