### ISSUE TITLE
抓包抓取到了token，并成功获取设备列表，但是集成显示无设备

### ISSUE THREAD

**Issue by LiuYaKu** [banto6/haier#102]
![image](https://github.com/banto6/haier/assets/32241120/24924287-5773-4429-bb48-ddd6d3c06ff9)

抓包的请求记录：（为了隐私，我把accessToken统一换成fa792a84--------------了）
[请求抓包详情.txt](https://github.com/banto6/haier/files/15167300/default.txt)

海尔集成日志
[home-assistant_haier_2024-04-30T15-21-37.975Z.log](https://github.com/banto6/haier/files/15167313/home-assistant_haier_2024-04-30T15-21-37.975Z.log)

辛苦您看一下

ps：提供一个获取accessToken的办法，只适用于iphone
1. app store下载stream
2. 在stream里面点击开始抓包，跟着步骤，完成配置
3. 开始抓包以后，点开微信，搜索海尔智家app小程序，然后登陆
4. 登陆完成以后，回到stream点击停止抓包，点击抓包历史，找到自己的抓包记录，搜索accessToken，随便点击一个请求，查看请求体就有accessToken了

**Comment by ERRORCODE6** [comment]
一样的问题啊
![搜狗截图20240430234752](https://github.com/banto6/haier/assets/92565101/d78b5f39-5eb6-4e6d-8cd2-047ed8b395a2)

**Comment by banto6** [comment]
@LiuYaKu 尝试去把`haier/core/client.py`中`CLIENT_ID`从`iOS17411714395440369`改为你请求包中的`iOS17411714489634666`试试呢

**Comment by redhatme** [comment]
> @LiuYaKu 尝试去把`haier/core/client.py`中`CLIENT_ID`从`iOS17411714395440369`改为你请求包中的`iOS17411714489634666`试试呢

改下这个就可以了。

**Comment by LiuYaKu** [comment]
> @LiuYaKu 尝试去把`haier/core/client.py`中`CLIENT_ID`从`iOS17411714395440369`改为你请求包中的`iOS17411714489634666`试试呢

没问题了

**Comment by LiuYaKu** [comment]
@banto6 辛苦大佬再加一个CLIENT_ID的输入参数吧😄

**Comment by dz515704201** [comment]
在小程序里也没显示出空调
