### ISSUE TITLE
设置失败，没有设备或实体

### ISSUE THREAD

**Issue by ERRORCODE6** [banto6/haier#103]
改了自己的clientId，可以保存token ,但是设置失败
[home-assistant_haier_2024-04-30T16-22-03.259Z.log](https://github.com/banto6/haier/files/15168030/home-assistant_haier_2024-04-30T16-22-03.259Z.log)
![搜狗截图20240501002310](https://github.com/banto6/haier/assets/92565101/d8a9e320-2e79-4175-804c-6496232c05ee)

**Comment by LiuYaKu** [comment]
抓包请求里面有获取到设备id list吗？

**Comment by ERRORCODE6** [comment]
> 抓包请求里面有获取到设备id list吗？
抓到了设备id型号啥的，都有

**Comment by ERRORCODE6** [comment]
重新下载新的master  已经成功解决问题
