### ISSUE TITLE
新版本 实体内容变少了很多 是因为小程序API变更了么? 以前热水器有好多实体和传感器

### ISSUE THREAD

**Issue by xxlxmd** [banto6/haier#104]
**问题描述**

**环境信息:**
 - Homeassistant版本: [e.g. 2024.4.2]

**设备信息**
若是设备无法识别或控制错误则此项**必填**。

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

**错误日志**

**Comment by banto6** [comment]
API变动导致的

**Comment by hsy5571615** [comment]
刚才用新的API接入了，确实少了很多实体和传感器，感觉小程序是轻量化的，给的信息本来就残缺，完整的还是得通过APP才能获取

**Comment by mayue1020** [comment]
> 新的API好多bug啊 洗衣机莫名其妙出现很多重复的实体 实体有时会突然不可用 微信小程序抓包没抓到access token 用智家app才抓到的,不知道会不会有问题

看了下好像token值都一样

**Comment by sasukebinbin** [comment]
> > 新的API好多bug啊 洗衣机莫名其妙出现很多重复的实体 实体有时会突然不可用 微信小程序抓包没抓到access token 用智家app才抓到的,不知道会不会有问题
> 
> 看了下好像token值都一样

那就是api本身的问题了. 现在奇怪的现象是只能加一个设备,另一个会自动变不可用.

**Comment by banto6** [comment]
关于少了部分实体和传感器这个问题暂时无解，因为APP版本我暂时没有抓到是如何通讯的，也因为时间问题，所以暂时放弃了。

**Comment by banto6** [comment]
修复了部分传感器未能正常加载的问题，可以试试最新代码
