### ISSUE TITLE
认证失败

### ISSUE THREAD

**Issue by 17686481412** [banto6/haier#105]
`**问题描述**`

登录界面认证失败
**环境信息:**
 - Homeassistant版本: [e.g. 2023.6.2]

**设备信息**
若是设备无法识别或控制错误则此项**必填**。

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

**错误日志**

**Comment by banto6** [comment]
see https://github.com/banto6/haier/issues/98
