### ISSUE TITLE
空调识别不到？

### ISSUE THREAD

**Issue by miaoyanginfo** [banto6/haier#107]
**问题描述**

**环境信息:**
 - Homeassistant版本: [e.g. 2024.4.4]

**设备信息**
若是设备无法识别或控制错误则此项**必填**。
挂式空调KFR-35G/NKB22A
以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

**错误日志**

**Comment by banto6** [comment]
缺少错误日志，无法排查
