### ISSUE TITLE
无法加载设备，提示设置失败

### ISSUE THREAD

**Issue by fenglingR** [banto6/haier#108]
**问题描述**
设置失败，所有设备无法调用，重新登录失效。
更新账户无用。

**环境信息:**
 - Homeassistant版本: [e.g. 2024.4.4]

**设备信息**
若是设备无法识别或控制错误则此项**必填**。

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
**错误日志**
此错误来自自定义集成。

日志: custom_components.haier.config_flow
来源: custom_components/haier/config_flow.py:92
集成: Haier (文档, 问题)
首次发生: 21:52:58 (2 全部发生)
上次记录: 21:53:01

uhome_token_request_error

**Comment by socekin** [comment]
+1

> **问题描述** 设置失败，所有设备无法调用，重新登录失效。 更新账户无用。
> 
> **环境信息:**
> 
> * Homeassistant版本: [e.g. 2024.4.4]家庭助理版本：[例如2024年4月4日]
> 
> **设备信息** 若是设备无法识别或控制错误则此项**必填**。
> 
> 以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
> 
> ```
> **错误日志**
> 此错误来自自定义集成。
> 
> 日志: custom_components.haier.config_flow
> 来源: custom_components/haier/config_flow.py:92
> 集成: Haier (文档, 问题)
> 首次发生: 21:52:58 (2 全部发生)
> 上次记录: 21:53:01
> 
> uhome_token_request_error
> ```
