### ISSUE TITLE
关于冰箱 “速冻锁鲜”和“智能存储”功能时，HA开关状态打架的解决思路

### ISSUE THREAD

**Issue by qiaohewei** [banto6/haier#11]
<img width="1076" alt="image" src="https://github.com/banto6/haier/assets/21193340/ffd76be1-50dc-4547-8f39-60badda2c749">

当操作上述两个按钮时候，APP端会实时给与响应，但是HA中，开关状态会变化。

根据多次复现，发现与15S 数据刷新有关。

建议的解决思路是，当操作这两个按钮后，马上进行接口数据刷新，就可以解决打架的问题。

可尝试以这种方式解决上述问题

**Comment by banto6** [comment]
问题1正在解决中

问题2暂时不考虑实现，除非大部分冰箱都适用

**Comment by banto6** [comment]
目前数据已支持实时更新，可尝试使用最新版本
