### ISSUE TITLE
认证失败

### ISSUE THREAD

**Issue by halfteas** [banto6/haier#111]
**问题描述**
认证失败
![IMG_0491](https://github.com/banto6/haier/assets/166982871/ad37575c-264a-4ce9-831e-57c539736926)

**环境信息:**
 - Homeassistant版本: [e.g. 2024.4.3]

**设备信息**
若是设备无法识别或控制错误则此项**必填**。

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

**错误日志**

**Comment by leikes996** [comment]
我也遇到了这个问题

**Comment by banto6** [comment]
see https://github.com/banto6/haier/issues/98
