### ISSUE TITLE
设置失败（认证失败）

### ISSUE THREAD

**Issue by xb4876** [banto6/haier#112]
**问题描述**

**环境信息:**
 - Homeassistant版本: [2024.5.0]

**错误日志**
浏览器返回信息："errors":{"base":"auth_error"} 
后台日志打印：2024-05-02 23:12:28.266 WARNING (MainThread) [custom_components.haier.config_flow] uhome_token_request_error
![haier](https://github.com/banto6/haier/assets/18182812/391eeeee-8534-4003-aa37-069306e3f78e)

**Comment by banto6** [comment]
see https://github.com/banto6/haier/issues/98
