### ISSUE TITLE
小程序api接入的设备设置问题

### ISSUE THREAD

**Issue by roycho93** [banto6/haier#114]
**问题描述**

海尔风管机通过新的api终于可以显示出设备了，感谢作者的付出。但是目前用下来会出现很多选项，能用的好像只有开关机，像调节温度的话还没找到怎么调节，请问可以优化吗，可以的话我需要提供什么资料？
![1714758876729](https://github.com/banto6/haier/assets/50717235/fa5c17bd-babe-4f3b-99c2-369a8fdbc647)

**Comment by roycho93** [comment]
刚刚发现需要通过打开空调，让小程序温度调节处于可调状态，重新添加设备可以出现温度调节。但风速以及空调模式（制冷制热）等暂时还无法调节。

**Comment by banto6** [comment]
用最新master分支代码试试

**Comment by roycho93** [comment]
> 用最新master分支代码试试

刚刚试了下，问题已经得到解决，感谢！
