### ISSUE TITLE
海尔热泵调温显示错误、零冷水功能关闭无效

### ISSUE THREAD

**Issue by xiaobinbinlzy** [banto6/haier#115]
**问题描述**

海尔热泵调温显示错误、零冷水功能关闭无效

<img width="332" alt="image" src="https://github.com/banto6/haier/assets/59834625/8717698e-8789-4a8e-8d5a-22681e244abe">
调整温度后，APP生效了。这里一起是显示43度
<img width="342" alt="image" src="https://github.com/banto6/haier/assets/59834625/e79743ba-e11d-4420-975d-a68fb6bae873">
零冷水功能关无效。。

**环境信息:**
 - Homeassistant版本: [e.g. 2025.5.1]

**设备信息**
若是设备无法识别或控制错误则此项**必填**。

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

**错误日志**

[home-assistant_haier_2024-05-03T19-01-46.714Z.log](https://github.com/banto6/haier/files/15204106/home-assistant_haier_2024-05-03T19-01-46.714Z.log)

**Comment by banto6** [comment]
调整温度后，APP生效了。这里一起是显示43度

**试试master最新代码**

零冷水功能关无效。。

**怎么个无效法？机器本身有没有零冷水功能**

**Comment by xiaobinbinlzy** [comment]
收到，谢谢。

原来原来代码是可以执行零冷水功能，也可以使用关取消它。。

**Comment by banto6** [comment]
提供一下设备信息和点击零冷水按钮后的运行日志呢

设备信息可在.storage/haier/目录下找到，文件格式为device_设备ID.json，上传文件时可将文件名和文件内容中的设备ID替换为任意值以保护个人隐私。

设备ID可开启debug模式后可在Device Info部分的日志中找到。日志可在配置 > 系统 > 日志 > 加载完整日志中查看。

**Comment by xiaobinbinlzy** [comment]
你好，最新的功能正常。 平时用得最多是调温和零冷水功能。。谢谢
