### ISSUE TITLE
WARNING (ImportExecutor_0) [homeassistant.helpers.typing]的问题

### ISSUE THREAD

**Issue by jiqigo** [banto6/haier#117]
测试修改 bianary_sensor.py等6个py 中:
from _homeassistant.helpers.typing_ import _HomeAssistantType_
改为：from _homeassistant.core_ import _HomeAssistant_
async def async_setup_entry(hass: _HomeAssistantType_, entry:......
改为：async def async_setup_entry(hass: _HomeAssistant_, entry: ......
后不再提示Deprecated HomeAssistantType。
大佬，这样会影响其他的问题吗？

**Comment by banto6** [comment]
fixed
