### ISSUE TITLE
海尔早期的净水器7502-4是接入阿里智能，不知道能否接入

### ISSUE THREAD

**Issue by gky008** [banto6/haier#122]
**前言**
- 请自行搜索历史issues是否存在相同问题
- 尽量按格式填写Issues模版中的必要信息，没有这些信息就算提交了也解决不了任何问题。

**问题描述**

**环境信息:**
 - Homeassistant版本: [e.g. 2023.6.2]

**设备信息**
若是设备无法识别或控制错误则此项**必填**，没有设备信息可能会被直接关闭不做处理。

设备信息可在`.storage/haier/`目录下找到，文件格式为`device_设备ID.json`，上传文件时可将文件名和文件内容中的`设备ID`替换为任意值以保护个人隐私。

设备ID可开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。

**错误日志**
若是运行报错或操控异常则日志**必填**，没有日志可能会被直接关闭不做处理。

**Comment by banto6** [comment]
配置好后没有看到指定设备就是不支持
