### ISSUE TITLE
使用master分支，没有water_heater实体

### ISSUE THREAD

**Issue by jiqigo** [banto6/haier#126]
问题描述
根据问题#110，下载使用master分支，我这里没有water_heater实体。
环境信息:
Homeassistant版本: 2024.5.0/1
设备信息
海尔热水器JSQ30-16R3BWU1
deviceType:18015007
productCodeT:GD0RD9004
productNameT:JSQ30-16R3BWU1
wifiType:201c120000118674181500418006360000000000000000000000000000000040
[device_************.json](https://github.com/banto6/haier/files/15221740/device_.json)

**Comment by staritbusfans** [comment]
可以测试一下我修改的分支，看下能否正常使用water_heater
https://github.com/staritbusfans/haier

**Comment by jiqigo** [comment]
> 可以测试一下我修改的分支，看下能否正常使用water_heater https://github.com/staritbusfans/haier
刚下载安装了，还是没有。但是另外一台JSQ30-16WN7S(12T)U1的就有water_heater的实体。

**Comment by staritbusfans** [comment]
看了一下你的燃气热水器json，没有出水温度字段，可能需要一些特殊处理😥

**Comment by jiqigo** [comment]
@staritbusfans 
刚测试了，GasWaterHeater实体有了，出水温度=设置温度。
再次感谢！

**Comment by jiqigo** [comment]
@staritbusfans 如果能把away_mode定义成循环方式就更好啦。(✿◠‿◠)
