### ISSUE TITLE
更新v1.0.0-alpha 版本之后部分设备识别错误

### ISSUE THREAD

**Issue by shaokui-gu** [banto6/haier#127]
**问题描述**
更新v1.0.0-alpha 版本之后部分设备识别错误，如：零冷水模式切换switch变成了sensor导致无法设置运行模式，目标温度number也变成了sensor无法设置温度

**环境信息:**
 - Homeassistant 
 - Supervisor  2024.04.4
 - Core 2024.5.1

**设备信息**
[device_1457.json](https://github.com/banto6/haier/files/15224691/device_1457.json)

**错误日志**

**Comment by ERRORCODE6** [comment]
用master分支的啊

**Comment by banto6** [comment]
![image](https://github.com/banto6/haier/assets/13196831/b1059ff4-0b35-4477-be87-ae724e99f8bc)
![image](https://github.com/banto6/haier/assets/13196831/ce1dd147-7f50-4358-9a92-b6ae34a092c8)

根据海尔返回的设备信息，这两个字段是不可写的，所以会被识别为sensor。你把Device Info 贴上来吧， 我看能不能特殊处理一下。

**Comment by staritbusfans** [comment]
我这边空气能热水器也是一样，设定温度、双源速热这些在热水器开机时writable为True，关机时为False，集成加载的时候如果热水器开着就会被认为是switch，关着就会被认做Sensor

**Comment by shaokui-gu** [comment]
> ![image](https://private-user-images.githubusercontent.com/13196831/328357460-b1059ff4-0b35-4477-be87-ae724e99f8bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODk0MDQsIm5iZiI6MTcxNTA4OTEwNCwicGF0aCI6Ii8xMzE5NjgzMS8zMjgzNTc0NjAtYjEwNTlmZjQtMGIzNS00NDc3LWJlODctYWU3MjRlOTlmOGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEzMzgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMzJkY2NiNDE5OTJmODQ0NmI4NmFjMWM0YjA2OTU2NjRlNWE4MDA1YjZhZTI2OTYyNDgyM2RhNTFlMGQxMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w8vaeZeAtGhIBN-TQd0FhO7u13gweJHQNIQmR1R5iJg) ![image](https://private-user-images.githubusercontent.com/13196831/328357555-ce1dd147-7f50-4358-9a92-b6ae34a092c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODk0MDQsIm5iZiI6MTcxNTA4OTEwNCwicGF0aCI6Ii8xMzE5NjgzMS8zMjgzNTc1NTUtY2UxZGQxNDctN2Y1MC00MzU4LTlhOTItYjZhZTM0YTA5MmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEzMzgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzM2NiZjdkMjQ3NzM4ZTAyN2VkODgyZTBlY2U1YmYxNTk1YzM2MjhiMWYzOWZhYmZmYTI1ZTk0YTQ2MWYzM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kCp3ryowQWcItCn-KWEkKWFozujZ5Zf0-z_0VtldCN8)
> 
> 根据海尔返回的设备信息，这两个字段是不可写的，所以会被识别为sensor。你把Device Info 贴上来吧， 我看能不能特殊处理一下。

您说的是设备的具体型号和设备id这些吗？都发给您，辛苦
![IMG_3149](https://github.com/banto6/haier/assets/83857593/1dd4de62-2801-4d1c-84cf-ed8e2091294e)

**Comment by banto6** [comment]
@shaokui-gu 你可以先按这个方法，在热水器开机的情况下启动集成试试 https://github.com/banto6/haier/issues/127#issuecomment-2097195931

**Comment by shaokui-gu** [comment]
@banto6 好的
