### ISSUE TITLE
礼貌咨询: 请问Access_Token是指的小程序的Access_Token吗

### ISSUE THREAD

**Issue by sunshinenny** [banto6/haier#129]
[相关文档](https://developers.weixin.qq.com/miniprogram/dev/OpenApiDoc/mp-access-token/getAccessToken.html)
![image](https://github.com/banto6/haier/assets/29770949/2e7f9403-fef3-448f-b494-35ef0aed65cf)

礼貌咨询，请问大佬是这个Access_Token吗

如果是2小时过期的话，那我确实折腾不动了😂

如果不是的话，麻烦大佬回复“不是”，我再去找找

**Comment by banto6** [comment]
不是
