### ISSUE TITLE
冰箱接入报错

### ISSUE THREAD

**Issue by ffsszzll** [banto6/haier#13]
**问题描述**
感谢分享！我添加冰箱，设备筛选方式无反应，实体筛选报“Unknown error occurred”错误

**环境信息:**
 - Homeassistant版本: [e.g. 2023.7.1]

**日志信息**
Logger: custom_components.haier.haier
Source: custom_components/haier/haier.py:179
Integration: Haier ([documentation](https://github.com/banto6/haier), [issues](https://github.com/banto6/haier/issues))
First occurred: 12:17:34 (1 occurrences)
Last logged: 12:17:34

获取配置信息失败, wifi_type: 111c120024000810010400618003474300000000000061800312430000000000, response: {"status": "1", "data": null, "total": 0}
-----------------------------------------------------------------
Logger: custom_components.haier
Source: custom_components/haier/haier.py:181
Integration: Haier ([documentation](https://github.com/banto6/haier), [issues](https://github.com/banto6/haier/issues))
First occurred: 12:17:34 (1 occurrences)
Last logged: 12:17:34

设备[DC330DB0D991]初始化失败
Traceback (most recent call last):
  File "/config/custom_components/haier/__init__.py", line 43, in async_setup_entry
    specs = await client.get_hardware_config(device.wifi_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/haier.py", line 181, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.haier.HaierClientException: 获取配置文件失败

**Comment by banto6** [comment]
账户中只有一个冰箱设备吗？

**Comment by ffsszzll** [comment]
是的，只有一个冰箱



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月8日(周六) 中午12:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [banto6/haier] 冰箱接入报错 (Issue #13)




 
账户中只有一个冰箱设备吗？

**Comment by banto6** [comment]
那主要问题是由于没有拉取到设备配置文件导致的，目前暂时无解，等我逆向海尔智家APP吧

**Comment by ffsszzll** [comment]
谢谢！只有暂时继续用Node-RED了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月8日(周六) 下午5:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [banto6/haier] 冰箱接入报错 (Issue #13)




 
那主要问题是由于没有拉取到设备配置文件导致的，目前暂时无解，等我逆向海尔智家APP吧

**Comment by 13860605362** [comment]
> 那主要问题是由于没有拉取到设备配置文件导致的，目前暂时无解，等我逆向海尔智家APP吧

大佬辛苦，node-red最近不知道为啥不行了。我只能期待这边更新后接入了。。。
