### ISSUE TITLE
显示失败

### ISSUE THREAD

**Issue by mzwbm** [banto6/haier#132]
**前言**
- 请自行搜索历史issues是否存在相同问题
- 尽量按格式填写Issues模版中的必要信息，没有这些信息就算提交了也解决不了任何问题。

**问题描述**
显示失败

**环境信息:**
 - Homeassistant版本: [e.g. 2023.6.2]
Core
2024.5.2
Frontend【前端】
20240501.1
**设备信息**
若是设备无法识别或控制错误则此项**必填**，没有设备信息可能会被直接关闭不做处理。

设备信息可在`.storage/haier/`目录下找到，文件格式为`device_设备ID.json`，上传文件时可将文件名和文件内容中的`设备ID`替换为任意值以保护个人隐私。

设备ID可开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。

**错误日志**
Error setting up entry Haier: 9ae5e3 for haier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/__init__.py", line 33, in async_setup_entry
    await store.async_save(json.dumps(await client.get_digital_model(device.id), ensure_ascii=False))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/core/client.py", line 87, in get_digital_model
    return json.loads(content['detailInfo'][deviceId])['attributes']
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: '68E4783FFB70'

**Comment by banto6** [comment]
使用master分支最新代码后看看最新日志

**Comment by mzwbm** [comment]
用了Master分支就正常了，谢谢

**Comment by banto6** [comment]
我只是把错误屏蔽掉了，你的设备下应该没有实体

**Comment by banto6** [comment]
应该有一个设备识别是异常的

**Comment by mzwbm** [comment]
不知道啊，反正我现在使用中的设备是都识别的，我帐号里本来就是一个待配网的设备，不过是爸妈家里的联不上网络，就没管它了，会不会是它

**Comment by banto6** [comment]
可能是的
