### ISSUE TITLE
token有效期只有7天，是否有自动获取token的方法，或者有效期更长的验证方式

### ISSUE THREAD

**Issue by LiuYaKu** [banto6/haier#135]
**问题描述**
token有效期只有7天，意味着每7天需要自己手动更新一次token，是否有自动获取token的方法，或者有效期更长的验证方式

**环境信息:**
 - Homeassistant版本: [12.2]

**设备信息**
无

**错误日志**
无

**Comment by banto6** [comment]
没有，暂时无解

**Comment by bloodmao1** [comment]
请教如何获取 token 和 id?

**Comment by gengleo** [comment]
> 请教如何获取 token 和 id?

同问

**Comment by gtds916** [comment]
> 请教如何获取 token 和 id?

同求大佬出教程

**Comment by zhyf0610** [comment]
BV1jZ42177zH

**Comment by zhyf0610** [comment]
> 请教如何获取 token 和 id?

BV1jZ42177zH

**Comment by zhyf0610** [comment]
> > 请教如何获取 token 和 id?
> 
> BV1jZ42177zH

目前测试windows和Android都能用这个软件找到，就是android稍微费点劲

**Comment by AndrewDufresne** [comment]
> > 请教如何获取 token 和 id?
> 
> BV1jZ42177zH

请问这是啥意思？

**Comment by banto6** [comment]
后续会将token获取相关的接口更换为海尔智家APP的，替换后理论可以长时间不过期，其他接口不变

**Comment by x64life** [comment]
> 后续会将token获取相关的接口更换为海尔智家APP的，替换后理论可以长时间不过期，其他接口不变

期待

**Comment by gtds916** [comment]
建议大神出个直接扫码出现token和ID的，这方面可以参考alist帮助文档哪种的，十分感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月13日(周一) 晚上11:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [banto6/haier] token有效期只有7天，是否有自动获取token的方法，或者有效期更长的验证方式 (Issue #135)




  
后续会将token获取相关的接口更换为海尔智家APP的，替换后理论可以长时间不过期，其他接口不变
  
期待

**Comment by dwxiayi** [comment]
> 后续会将token获取相关的接口更换为海尔智家APP的，替换后理论可以长时间不过期，其他接口不变

我抓包看了一下，小程序的逻辑应该是获取设备列表失败后自动用老的token提交本地生成的新token。
更新api为
curl -X POST -H "Host:zj.haier.net" -H "Connection:keep-alive" -H "Content-Length:51" -H "charset:utf-8" -H "clientid:Android13171453551" -H "sign:3581b6d17af1ae3769e237603cdbb36b8b8eff7d1c7ebf81fc0dc9019f2a8417" -H "User-Agent:Mozilla/5.0 (Linux; Android 13; 2211133C Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.99 XWEB/4433 MMWEBSDK/20230805 Mobile Safari/537.36 MMWEBID/9733 MicroMessenger/8.0.42.2424(0x28002A43) WeChat/arm64 Weixin GPVersion/1 NetType/WIFI Language/zh_CN ABI/arm64 MiniProgramEnv/android" -H "accesstoken:3f67253684448a655413053174453" -H "ak:3f67253695f8444855413053174453" -H "Accept-Encoding:gzip,compress,br,deflate" -H "env:" -H "platform:sc-mp-wx-zjapp" -H "appid:MB-SHEZJAPPWXXCX-0000" -H "appkey:79ce99cc7f9804663939676031b8a427" -H "content-type:application/json;charset=UTF-8" -H "mg:uNgSn9XCVC7gELPIQ2sJ6MXcSqNnAENY" -H "timestamp:1715606022705" -H "accounttoken:3f67253695f84448a6554130531" -H "Referer:https://servicewechat.com/wxe24b2f1f4e3/271/page-frame.html" -d "{"accountToken":"3a520ea169f94d2f9ef0d144e7"}" "https://zj.haier.net/api-gw/oauthserver/applet/v1/userinfo/query"

**Comment by dwxiayi** [comment]
> 后续会将token获取相关的接口更换为海尔智家APP的，替换后理论可以长时间不过期，其他接口不变

我抓包看了一下，小程序的逻辑应该是获取设备列表失败后自动用老的token提交本地生成的新token。
更新api为
curl -X POST -H "Host:zj.haier.net" -H "Connection:keep-alive" -H "Content-Length:51" -H "charset:utf-8" -H "clientid:Android13171453551" -H "sign:3581b6d17af1ae3769e237603cdbb36b8b8eff7d1c7ebf81fc0dc9019f2a8417" -H "User-Agent:Mozilla/5.0 (Linux; Android 13; 2211133C Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.99 XWEB/4433 MMWEBSDK/20230805 Mobile Safari/537.36 MMWEBID/9733 MicroMessenger/8.0.42.2424(0x28002A43) WeChat/arm64 Weixin GPVersion/1 NetType/WIFI Language/zh_CN ABI/arm64 MiniProgramEnv/android" -H "accesstoken:3f67253684448a655413053174453" -H "ak:3f67253695f8444855413053174453" -H "Accept-Encoding:gzip,compress,br,deflate" -H "env:" -H "platform:sc-mp-wx-zjapp" -H "appid:MB-SHEZJAPPWXXCX-0000" -H "appkey:79ce99cc7f9804663939676031b8a427" -H "content-type:application/json;charset=UTF-8" -H "mg:uNgSn9XCVC7gELPIQ2sJ6MXcSqNnAENY" -H "timestamp:1715606022705" -H "accounttoken:3f67253695f84448a6554130531" -H "Referer:https://servicewechat.com/wxe24b2f1f4e3/271/page-frame.html" -d "{"accountToken":"3a520ea169f94d2f9ef0d144e7"}" "https://zj.haier.net/api-gw/oauthserver/applet/v1/userinfo/query"

**Comment by flyibeat** [comment]
> 后续会将token获取相关的接口更换为海尔智家APP的，替换后理论可以长时间不过期，其他接口不变

期待，非常感谢大佬付出

**Comment by ERRORCODE6** [comment]
> 后续将把token获取相关的接口更换为海尔智家APP的，替换后理论可以长时间不过期，其他接口不变

期待尽快安排，老要填token ,每次洗澡发现启动不了热水器，，

**Comment by roycho93** [comment]
> ~后续会将token获取相关的接口更换为海尔智家APP的，替换后理论可以长时间不过期，其他接口不变~
> 
> 实测发现用app端的token无法正常控制设备，app端的控制API暂时没有抓到。所以暂时搁置了

现在小程序的api除了token问题真的很好用，感谢作者的辛苦。目前还有任何别的想法可以实现不用每周抓包token吗？

**Comment by banto6** [comment]
[v1.1.0](https://github.com/banto6/haier/releases/tag/v1.1.0) 已实现
