### ISSUE TITLE
燃气热水器累计用气量和累计用水量显示有问题

### ISSUE THREAD

**Issue by lyfqdl** [banto6/haier#143]
![1](https://github.com/banto6/haier/assets/16411127/ff1649c8-4018-4b16-aca0-7576d8d4d662)
![2](https://github.com/banto6/haier/assets/16411127/288c42fd-46e5-45f6-9a43-94878584fb5c)
应该是没有换算，造成显示用量与实际用量不符

**Comment by banto6** [comment]
正确的值是多少？

**Comment by lyfqdl** [comment]
核实了下，用水量单位是L，没问题。
用气量单位是m³，应该除以1000

**Comment by banto6** [comment]
已修复
