### ISSUE TITLE
每天10:17定时开机状态打开

### ISSUE THREAD

**Issue by okwelcome** [banto6/haier#147]
![Screenshot_2024-06-04-19-18-14-708_com jiluxinqing ha](https://github.com/banto6/haier/assets/40828738/dc39b5b0-dd28-4e5f-901b-9cc28f6a1fd5)
安装了最新版的Haier集成，海尔燃气热水器功能正常，但每天上午10:17准时开机是bug还是集成设置好的？_`

**Comment by okwelcome** [comment]
![Screenshot_2024-06-04-19-18-14-708_com jiluxinqing ha](https://github.com/banto6/haier/assets/40828738/bd3208c1-a3f1-4919-a002-891b563c95ff)

**Comment by banto6** [comment]
非集成问题，检查APP自动化

**Comment by okwelcome** [comment]
自动化检查过了，ha，app，小程序都检查过没设置10:17开机

**Comment by okwelcome** [comment]
> 非集成问题，检查APP自动化

自动化检查过了，ha，app，小程序都检查过没设置10:17开机
