### ISSUE TITLE
是否考虑支持短信登录？

### ISSUE THREAD

**Issue by lightrabbit** [banto6/haier#152]
https://github.com/banto6/haier/issues/141#issuecomment-2141653898
在这个issue的讨论中，提到了一个短信登录的接口，可以通过手机号和短信验证码完成登录流程。
这样可以很大程度解决登录相关的问题。

**Comment by banto6** [comment]
目前登录已满足使用，不考虑短信登录

**Comment by tangtangxiao** [comment]
目前就是这个RefreshToken获取很麻烦。
