### ISSUE TITLE
登入账号密码显示认证失败

### ISSUE THREAD

**Issue by zhu-cucu** [banto6/haier#153]
最近几个月发现设置的燃气零冷水模式无法通过ha控制了，之前也遇到过，我就把ha系统升级到最新就可以了，但这次我把ha升级到最新版本也不行，然后我又重新安装插件，发现还是无法通过账号密码登入认证，不知道是不是服务器一样还是海尔改变api了。

<img width="587" alt="image" src="https://github.com/banto6/haier/assets/36913656/d0f9d5c6-6035-4186-95c4-f06d80225940">
<img width="528" alt="image" src="https://github.com/banto6/haier/assets/36913656/11833a79-2eb4-4e63-b263-658a99bcd73c">
<img width="373" alt="image" src="https://github.com/banto6/haier/assets/36913656/9013c151-7c01-4b7a-817b-fcd25edcc8ff">

**Comment by banto6** [comment]
请查看更新日志。
