### ISSUE TITLE
部分实体生成为传感器，无法操作

### ISSUE THREAD

**Issue by wangyz1997** [banto6/haier#157]
**问题描述**

首先感谢作者大大开发的优秀集成。在我将家中燃气热水器通过集成接入HA时，集成成功生成了App中对应所有功能的实体，但有些实体生成为了只读的`sensor`或`binary_sensor`，而非可操作的`switch` `select`或`number`。

**环境信息:**

 - Homeassistant版本: `2024.6.3`

**设备信息**

卡萨帝燃气热水器`JSQ31-16CRVBAU1`

[device_XXXX.json](https://gist.github.com/wangyz1997/da0c36aeb94ca0112d87d976a1c2b46e)

**预期效果**

下图所示的模式可以被控制。

![image](https://github.com/banto6/haier/assets/29337599/2226b36d-b7a5-4cd3-9428-ff7f727c89a2)

**Comment by banto6** [comment]
https://github.com/banto6/haier/issues/127#issuecomment-2097195931  在热水器开机状态下重载集成试试

**Comment by wangyz1997** [comment]
谢谢，已解决
