### ISSUE TITLE
空调设备信息收集

### ISSUE THREAD

**Issue by banto6** [banto6/haier#16]
**背景**

目前计划整合climate实体，需要尽可能多的空调配置文件以供评估实现的可能性。

**数据收集**

需要的信息如下，可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。

`Device Info`日志需要使用master分支代码或者`v0.1.0`开启debug模式才会显示。

```
deviceType:

productCodeT:

productNameT:

wifiType:
```

**请不会在此issue下回复无关信息，无关信息会直接隐藏。**

**目前Climate已推出Beta版。因为我没有海尔空调设备，所以无法测试。欢迎大家参与测试。**

**测试过程中遇到的问题欢迎提issue或加群891954983反馈**

**Comment by astangcong** [comment]
我有两台型号一样到卡萨帝空调已经接入，但是在日志里没有设备信息啊？

**Comment by banto6** [comment]
> 我有两台型号一样到卡萨帝空调已经接入，但是在日志里没有设备信息啊？ 2023-07-08 19:03:53.445 DEBUG (MainThread) [custom_components.haier.coordinator] 设备[04E2290XXXXX]已获取到最新状态数据: {"windSensingStatus": "false", "silentSleepStatus": "false", "humidificationStatus": "false", "intelligenceStatus": "false", "location": "", "messageVersion": "", "pm2p5ExceedRemind": "0", "electricHeatingStatus": "false", "ch2oValue": "0", "rapidMode": "false", "voiceSignStatus": "false", "specialMode": "0", "energySavePeriod": "15", "10degreeHeatingStatus": "false", "time": "00:00:00", "ch2oCleaningStatus": "false", "humanSensingStatus": "0", "outdoorPM2p5Value": "0", "scheduleVersion": "", "acType": "0", "playControl": "0", "lightStatus": "false", "dialect": "0", "totalCleaningTime": "0", "updateStatus": "false", "authVersion": "0", "errCode": "0", "totalElectricityUsed": "0", "tempUnit": "1", "sensingResult": "0", "currentMediaName": "", "lockStatus": "false", "clientId": "", "playProgress": "0", "selfCleaningStatus": "false", "runningMode": "1", "airQuality": "0", "playTime": "0", "operationModeHK": "0", "hardVersion": "", "voiceStatus": "false", "operationMode": "1", "playStatus": "false", "co2Value": "0", "targetTemperature": "27.00", "vocValue": "0", "energySavingStatus": "false", "localFilterChangeFlag": "false", "freshAirStatus": "false", "onOffStatus": "true", "windDirectionVertical": "5", "halfDegreeSettingStatus": "false", "date": "00:00:00", "echoStatus": "false", "freshWindSpeed": "0", "outdoorTemperature": "39.00", "uniqueId": "", "pm2p5Level": "0", "voiceRecogMode": "0", "token": "", "currentSongFavourited": "false", "voiceprintRecogStatus": "false", "humidityCtrlStatus": "false", "vboxId?": "", "co2ExceedRemind": "0", "indoorPM2p5Value": "0", "muteStatus": "false", "pmvStatus": "false", "healthMode": "false", "ErrAckFlag": "false", "pm2p5CleaningStatus": "false", "targetHumidity": "30", "softVersion": "", "indoorTemperature": "26.50", "windSpeed": "5", "heatAccumulationStatus": "false", "opSrc": "3", "playMode": "1", "volume": "100", "selfCleaning56Status": "false", "screenDisplayStatus": "true", "otaControl": "0", "windDirectionHorizontal": "7", "indoorHumidity": "46"} 2023-07-08 19:03:53.445 DEBUG (MainThread) [custom_components.haier.coordinator] Finished fetching Haier Device [04E2290XXXXX] data in 0.215 seconds (success: True)


您好，`Device Info`日志需要使用master分支代码或者`v0.1.0`开启debug模式才会显示。

**Comment by astangcong** [comment]
deviceType:02012036

productCodeT:AABMZD000

productNameT:CAS35GCA(81)U1室内机总成

wifiType:2008610800820324021200118006915900000000000000000000000000000040

**Comment by 408903653** [comment]
此错误来自自定义集成。

Logger: custom_components.haier
Source: custom_components/haier/haier.py:181 
Integration: Haier (documentation, issues) 
First occurred: 06:10:50 (12 occurrences) 
Last logged: 20:23:24

设备[DC330D4793D1]初始化失败
设备[0007A8E48CB1]初始化失败
Traceback (most recent call last):
  File "/config/custom_components/haier/__init__.py", line 43, in async_setup_entry
    specs = await client.get_hardware_config(device.wifi_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier/haier.py", line 181, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.haier.HaierClientException: 获取配置文件失败

**Comment by 408903653** [comment]
大神你好，我这个能识别出来，我的洗衣机和空调，就是实体没有

**Comment by 408903653** [comment]
![Uploading 708BDDA6-C66E-4ABB-9AF5-45B1FF3AEA59.png…]()

**Comment by 408903653** [comment]
![Uploading 30C96FAF-15C9-4E32-B448-659A07169B5F.png…]()

**Comment by banto6** [comment]
> 大神你好，我这个能识别出来，我的洗衣机和空调，就是实体没有

主要问题是由于没有拉取到设备配置文件导致的，目前暂时无解，等我逆向海尔智家APP吧

**Comment by Xi11-github** [comment]
deviceType:0201205i

productCodeT:AAC7C1000

productNameT:KFR-35G/LAA81U1室内机总成

wifiType:2008610800820324021200118008325200000000000000000000000000000040


deviceType:03001001

productCodeT:AA9KTB015

productNameT:KFR-35G/WEC21AU1室内机总成

wifiType:00000000000000008080000000041410

**Comment by Xi11-github** [comment]
deviceType:03001001

productCodeT:AA9KTB015

productNameT:KFR-35G/WEC21AU1室内机总成

wifiType:00000000000000008080000000041410

**Comment by aihhkc** [comment]
deviceType:0201201G
productCodeT:AAABTB00E
productNameT:KFR-26G/KBB83U1室内机总成
wifiType:2008610800820324021200118007264200000000000000000000000000000040

deviceType:0D012001
productCodeT:AA9KK9007
productNameT:KFRD-72NW/64DDA21Z
wifiType:201c1200240008100d12f71c4094f300000080e384181627a2904f4940b24240

deviceType:0D012001
productCodeT:AA9KK7007
productNameT:KFRD-36NW/61DBA21Z
wifiType:201c1200240008100d12f71c4094f300000080e384181627a2904f4940b24240

**Comment by llgxdnn** [comment]
deviceType: 02011002

productCodeT: AAABTJ006

productNameT: KFR-35G/KBA81U1室内机总成

wifiType: 201c12002400081002111169c9cf44a02ea320b9520d1c18e042f62c18420c40

**Comment by dingzhenying** [comment]
deviceType: 0D082001

productCodeT: AA9E9005A

productNameT: RFTSAD71MXS-V1

wifiType: 01c12002400081034080000000100000

**Comment by fenglou777** [comment]
此错误来自自定义集成。

Logger: custom_components.haier
Source: custom_components/haier/__init__.py:42 
Integration: Haier (documentation, issues) 
First occurred: 2023年7月12日 17:42:37 (2 occurrences) 
Last logged: 2023年7月12日 17:42:37

设备[DC330DC159ED_1-1]初始化失败
设备[DC330DC159ED_1-2]初始化失败
Traceback (most recent call last):
  File "/config/custom_components/haier/__init__.py", line 42, in async_setup_entry
    sw_version = (await client.get_net_quality_by_device(device.id))['hardwareVers']
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'hardwareVers'

**Comment by FaintGhost** [comment]
> @astangcong @llgxdnn @aihhkc @Xi11-github @FaintGhost 最新master分支代码已新增beta版本climate实体，因为我没有海尔的空调设备，所有没办法测试。各位可以拉取最新的代码测试一下功能，功能有问题新开issue即可。

更新重启之后，两个空调的climate实体均处于不可用状态，报错日志如下：
```
2023-07-13 23:08:15.177 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform haier
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 504, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 812, in _async_write_ha_state
attr.update(self.state_attributes or {})
^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 295, in state_attributes
ATTR_CURRENT_TEMPERATURE: show_temp(
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/temperature.py", line 24, in display_temp
raise TypeError(f"Temperature is not a number: {temperature}")
TypeError: Temperature is not a number: 29.00
2023-07-13 23:08:15.197 ERROR (MainThread) [homeassistant.components.climate] Error while setting up haier platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 504, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 812, in _async_write_ha_state
attr.update(self.state_attributes or {})
^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 295, in state_attributes
ATTR_CURRENT_TEMPERATURE: show_temp(
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/temperature.py", line 24, in display_temp
raise TypeError(f"Temperature is not a number: {temperature}")
TypeError: Temperature is not a number: 29.00
```

**Comment by banto6** [comment]
> > @astangcong @llgxdnn @aihhkc @Xi11-github @FaintGhost 最新master分支代码已新增beta版本climate实体，因为我没有海尔的空调设备，所有没办法测试。各位可以拉取最新的代码测试一下功能，功能有问题新开issue即可。
> 
> 更新重启之后，两个空调的climate实体均处于不可用状态，报错日志如下：
> 
> ```
> 2023-07-13 23:08:15.177 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform haier
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 504, in async_add_entities
> await asyncio.gather(*tasks)
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
> await entity.add_to_platform_finish()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in add_to_platform_finish
> self.async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
> self._async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 812, in _async_write_ha_state
> attr.update(self.state_attributes or {})
> ^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 295, in state_attributes
> ATTR_CURRENT_TEMPERATURE: show_temp(
> ^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/helpers/temperature.py", line 24, in display_temp
> raise TypeError(f"Temperature is not a number: {temperature}")
> TypeError: Temperature is not a number: 29.00
> 2023-07-13 23:08:15.197 ERROR (MainThread) [homeassistant.components.climate] Error while setting up haier platform for climate
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
> await asyncio.gather(*pending)
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 504, in async_add_entities
> await asyncio.gather(*tasks)
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
> await entity.add_to_platform_finish()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in add_to_platform_finish
> self.async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
> self._async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 812, in _async_write_ha_state
> attr.update(self.state_attributes or {})
> ^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 295, in state_attributes
> ATTR_CURRENT_TEMPERATURE: show_temp(
> ^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/helpers/temperature.py", line 24, in display_temp
> raise TypeError(f"Temperature is not a number: {temperature}")
> TypeError: Temperature is not a number: 29.00
> ```

再试试呢

**Comment by banto6** [comment]
@FaintGhost 拉一下最新代码试试呢

**Comment by FaintGhost** [comment]
> @FaintGhost 拉一下最新代码试试呢

climate实体正常工作了，我这两天测试一下各个功能是否正常工作，感谢大佬的辛苦工作！另外发现传感器部分出现了一部分不可用的实体，这是否代表空调不具备这些功能呢？

**Comment by banto6** [comment]
> > @FaintGhost 拉一下最新代码试试呢
> 
> climate实体正常工作了，我这两天测试一下各个功能是否正常工作，感谢大佬的辛苦工作！另外发现传感器部分出现了一部分不可用的实体，这是否代表空调不具备这些功能呢？

`不可用的实体`这个问题可以截图新开个issue我看看

**Comment by dingzhenying** [comment]
拉取最新代码后，空调设备无法加载出来了，报错如下：
2023-07-15 11:12:18.620 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Haier: 15552211520 for haier
Traceback (most recent call last):
File "/Users/dingzhenying/.homeassistant/lib/python3.11/site-packages/homeassistant/config_entries.py", line 387, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dingzhenying/.homeassistant/custom_components/haier/__init__.py", line 31, in async_setup_entry
devices = await get_available_devices(client)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dingzhenying/.homeassistant/custom_components/haier/__init__.py", line 102, in get_available_devices
devices = await client.get_devices() + await get_virtual_devices(client)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dingzhenying/.homeassistant/custom_components/haier/core/client.py", line 89, in get_devices
await device.async_init()
File "/Users/dingzhenying/.homeassistant/custom_components/haier/core/device.py", line 62, in async_init
self._sw_version = (await self._client.get_net_quality_by_device(self.id))['hardwareVers']
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'hardwareVers'

**Comment by yangrusen** [comment]
2023-07-17 09:56:21.424 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 00000000000000008080000000041410, response: {"status": "1", "data": null, "total": 0}
2023-07-17 09:56:21.426 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败
Traceback (most recent call last):
  File "/config/custom_components/haier/core/device.py", line 68, in async_init
    properties = (await self._client.get_hardware_config(self.wifi_type))['Property']
  File "/config/custom_components/haier/core/client.py", line 153, in get_hardware_config
    raise HaierClientException('获取配置文件失败')
custom_components.haier.core.client.HaierClientException: 获取配置文件失败
2023-07-17 09:56:21.428 ERROR (MainThread) [custom_components.haier] Device [AC8226B859AE] 未获取到可用attribute

**Comment by Wooo0** [comment]
'deviceType': '03001001',
'productCodeT': 'AB8Y74000'
'productNameT': 'KFR-72L/UDP21AU1室内机总成',
'wifiType': '00000000000000008080000000041410'
 设备初始化失败

**Comment by banto6** [comment]
> 拉取最新代码后，空调设备无法加载出来了，报错如下： 2023-07-15 11:12:18.620 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Haier: 15552211520 for haier Traceback (most recent call last): File "/Users/dingzhenying/.homeassistant/lib/python3.11/site-packages/homeassistant/config_entries.py", line 387, in async_setup result = await component.async_setup_entry(hass, self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/dingzhenying/.homeassistant/custom_components/haier/**init**.py", line 31, in async_setup_entry devices = await get_available_devices(client) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/dingzhenying/.homeassistant/custom_components/haier/**init**.py", line 102, in get_available_devices devices = await client.get_devices() + await get_virtual_devices(client) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/dingzhenying/.homeassistant/custom_components/haier/core/client.py", line 89, in get_devices await device.async_init() File "/Users/dingzhenying/.homeassistant/custom_components/haier/core/device.py", line 62, in async_init self._sw_version = (await self._client.get_net_quality_by_device(self.id))['hardwareVers']
> 
> ```
> KeyError: 'hardwareVers'
> ```

使用最新代码试试，还有问题的话新开一个issue

**Comment by banto6** [comment]
> 以前实体筛选能看到空调设备，没法控制。现在实体筛选里看不到设备了。
> 
> 2023-07-17 09:56:21.424 ERROR (MainThread) [custom_components.haier.core.client] 获取配置信息失败, wifi_type: 00000000000000008080000000041410, response: {"status": "1", "data": null, "total": 0} 2023-07-17 09:56:21.426 ERROR (MainThread) [custom_components.haier.core.device] 获取attributes失败 Traceback (most recent call last): File "/config/custom_components/haier/core/device.py", line 68, in async_init properties = (await self._client.get_hardware_config(self.wifi_type))['Property'] File "/config/custom_components/haier/core/client.py", line 153, in get_hardware_config raise HaierClientException('获取配置文件失败') custom_components.haier.core.client.HaierClientException: 获取配置文件失败 2023-07-17 09:56:21.428 ERROR (MainThread) [custom_components.haier] Device [AC8226B859AE] 未获取到可用attribute

提示`获取配置文件失败`表示设备跟当前API不兼容，暂时没有解决方案，目前正在考虑更换API，可以关注一下后续更新。

**Comment by dwxiayi** [comment]
Device Info: {'_raw_data': {'deviceId': '18A7F198C686', 'deviceName': '中央空调', 'deviceType': '0D012001', 'online': True, 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}], 'productCodeT': 'AA9KK9007', 'productNameT': 'KFRD-72NW/64DDA21Z', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '201c1200240008100d12f71c4094f300000080e384181627a2904f4940b24240'}} 
有climate实体，无法控制设备

**Comment by toutoumu** [comment]
一个四台,除客厅外其他三台型号一样的
{'_raw_data': {'deviceId': '1457907F21EE', 'deviceName': '客厅空调', 'deviceType': '0301200n', 'online': True, 'permissions': [{'auth': {'control': True, 'set': False, 'view': True}, 'authType': 'home'}], 'productCodeT': 'AB91SG003', 'productNameT': 'KFR-50L/LBC81U1室内机总成', 'totalPermission': {'control': True, 'set': False, 'view': True}, 'wifiType': '2008610800820324031200118011124100000000000000000000000000000040'}},

{'_raw_data': {'deviceId': 'A082225A9404', 'deviceName': '儿童房空调', 'deviceType': '02012036', 'online': True, 'permissions': [{'auth': {'control': True, 'set': False, 'view': True}, 'authType': 'home'}], 'productCodeT': 'AAABTT00M', 'productNameT': 'KFR-26G/KBB81U1室内机总成', 'totalPermission': {'control': True, 'set': False, 'view': True}, 'wifiType': '2008610800820324021200118006915900000000000000000000000000000040'}},

{'_raw_data': {'deviceId': 'A082225A649C', 'deviceName': '主卧空调', 'deviceType': '02012036', 'online': True, 'permissions': [{'auth': {'control': True, 'set': False, 'view': True}, 'authType': 'home'}], 'productCodeT': 'AAABTT00M', 'productNameT': 'KFR-26G/KBB81U1室内机总成', 'totalPermission': {'control': True, 'set': False, 'view': True}, 'wifiType': '2008610800820324021200118006915900000000000000000000000000000040'}},

{'_raw_data': {'deviceId': 'A082225A949A', 'deviceName': '老人房空调', 'deviceType': '02012036', 'online': True, 'permissions': [{'auth': {'control': True, 'set': False, 'view': True}, 'authType': 'home'}], 'productCodeT': 'AAABTT00M', 'productNameT': 'KFR-26G/KBB81U1室内机总成', 'totalPermission': {'control': True, 'set': False, 'view': True}, 'wifiType': '2008610800820324021200118006915900000000000000000000000000000040'}}

**Comment by luanzun** [comment]
可正常识别显示：
deviceType: 02011002
productCodeT: AAABN2000
productNameT: KFR-26G/SAA21AU1室内机总成
wifiType: 201c12002400081002111169c9cf44a02ea320b9520d1c18e042f62c18420c40

----
可识别，但没有生成实体：
'deviceType': '03001001'
'productCodeT': 'AB8Y7T007'
'productNameT': 'KFR-50L/EDS21AU1室内机总成'
'wifiType': '00000000000000008080000000041410'
