### ISSUE TITLE
默认加载设备时，部分设备的select方法被disable导致功能不可用，寻求咨询

### ISSUE THREAD

**Issue by sunshinenny** [banto6/haier#170]
**问题描述**
386型号的洗衣机使用小程序API，无法对洗衣程序进行控制。

可能获取到的选项是被 disable 导致的。

据观察，在洗衣机开机时候，重载集成。可以正常选择选项。
![重载前](https://github.com/user-attachments/assets/0e8e0839-f85e-40a1-a1e5-2dcec0022581)
![开机后重载](https://github.com/user-attachments/assets/a4d68b1f-5cd9-49fd-b105-9aa7e781e628)

**解决方案**
可以的话，在服务里新增“重载Haier”集成的方法，

这样我远程调用开机后，再调用重载。应该可以解决这个问题

**Comment by banto6** [comment]
后面抽时间加个reload功能
