### ISSUE TITLE
climate空调实体无法关闭

### ISSUE THREAD

**Issue by donh20** [banto6/haier#173]
**问题描述**

海尔智家插件标记为climate的空调设备可以正常打开，也可以调整设置温度，但是无法关闭
![image](https://github.com/user-attachments/assets/bf872a31-8ef9-434c-8409-24bb6e0d086a)
即在HA配置页面尝试关闭后，面板显示为关闭，但实际空调状态仍然是开启的。这个时候尝试设置风速和温度，空调仍然可以正常接收指令。

如果需要关闭的话，可以用相同设备下标记为switch的开关机状态来完成
![image](https://github.com/user-attachments/assets/840196f0-3112-43ae-b4f5-985d17dfcc02)

空调是日立的中央空调，一拖三，是海尔面板通过RS485协议控制的。离线控制正常，海尔智家控制正常。

另外还有一个补充信息，我在T日添加加客厅空调的时候发现有这个bug，T+1日在添加主卧和次卧空调时发现客厅空调的关闭功能居然好了，即在图一的climate控制面板选择关闭后，空调真的关闭了，不确定是否和重启群晖有关，我也会持续跟进相关用例。
目前状态是，客厅空调正常，主卧，次卧空调不正常。

除了空调无法正常关闭之外，其它设备都很丝滑，感谢作者！
**环境信息:**

20240726 黑群晖，DSM7.2 docker部署  homeassistant/home-assistant:latest 
haier插件版本1.1.0 

**设备信息**
若是设备无法识别或控制错误则此项**必填**，没有设备信息可能会被直接关闭不做处理。

设备信息可在`.storage/haier/`目录下找到，文件格式为`device_设备ID.json`，上传文件时可将文件名和文件内容中的`设备ID`替换为任意值以保护个人隐私。

设备ID可开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。

**错误日志**
无报错信息，如需要提供日志请告知，谢谢

**Comment by donh20** [comment]
再补充一个信息，实体的climate无法关闭，但是设备这里的开关机状态是可以操作的。怀疑这里的开关机状态调用了“switch的开关机状态”。

**Comment by banto6** [comment]
按模板提供一下问题空调的设备信息文件

**Comment by donh20** [comment]
[device_D8.json](https://github.com/user-attachments/files/16409578/device_D8.json)
[home-assistant_2024-07-29T08-25-33.314Z.log](https://github.com/user-attachments/files/16409859/home-assistant_2024-07-29T08-25-33.314Z.log)
分别尝试通过climate实体和switch实体控制空调，设备文件和日志如附件

**Comment by banto6** [comment]
先用master分支代码试试

**Comment by donh20** [comment]
看到这个问题在 #163 被修复了 (https://github.com/banto6/haier/pull/163)
我直接从项目主页(https://github.com/banto6/haier)的快速安装按钮进行了安装,我理解应该就是用的master分支
请问要如何更新呢

**Comment by donh20** [comment]
我先把climate.py下载下来试试

**Comment by donh20** [comment]
通过源码更新后问题解决
