### ISSUE TITLE
空调温度设定最大值最小值异常

### ISSUE THREAD

**Issue by yide-idles** [banto6/haier#175]
**问题描述**
遇到了和#57类似的问题，温度最小值锁定到0度，最大值锁定到14度。任何关于空调的操作（调节风力）都会将空调温度降至16度（设定最低）。

**环境信息:**
 - Homeassistant版本: 2024.7.3 

**设备信息**
[device_AAAA.json](https://github.com/user-attachments/files/16407598/device_AAAA.json)

**错误日志**
[home-assistant_2024-07-29T04-58-59.139Z.log](https://github.com/user-attachments/files/16407636/home-assistant_2024-07-29T04-58-59.139Z.log)

p.s. 
1、日志里开始的几处错误是我自己修改代码所致，后面恢复就不报错了。
2、日志里有  WARNING (SyncWorker_33) [custom_components.haier.select] Device [AAAA] attribute [windDirectionVertical] value [7] not recognizable类似的提示，从7.28日凌晨安装到现在出现了几万条。

**Comment by banto6** [comment]
<img width="326" alt="image" src="https://github.com/user-attachments/assets/34b4c8da-a1c6-4d89-813f-2175e7f1bec1">


0-14度为海尔云端返回的最大最小值，目前集成都是以云端配置为准，建议自行fork后给温度加个偏移量后使用

https://github.com/banto6/haier/blob/3699c4aca797879a8ad4db6ad27b656a54024dad/custom_components/haier/core/attribute.py#L173-L174

**Comment by yide-idles** [comment]
添加偏移量后，问题解决。谢谢
