### ISSUE TITLE
设备逻辑关机期间刷新token导致控制实体变成传感器实体

### ISSUE THREAD

**Issue by woyaya** [banto6/haier#181]
**前言**
已参考[#127]

**问题描述**
设备逻辑关机(电源、网络仍连通)情况下，token刷新会导致控制实体变成传感器实体

**问题场景**
长假期间关闭热水器，期间若token有刷新，则控制实体异常，相关控制自动化失效

**预期结果**
增加强制重刷token的服务
这样可以在自动化开始时，先开机，再强制刷新token，让异常实体重新变成控制实体

**Comment by banto6** [comment]
https://github.com/banto6/haier/commit/014ca1e50b905f5e627043f946e630177d76e437

已修复，可使用master分支试试

**初次启动集成的时候需要将所有设备的电源打开，集成识别正确后即可关闭设备电源**

**Comment by kenlgj** [comment]
Token和device ID配不上怎么办
