### ISSUE TITLE
海尔云暖空气能线控器不能设置温度

### ISSUE THREAD

**Issue by benshenhehe** [banto6/haier#184]
大神，我空气能线控器无法设置温度，学了一个周的ha直接泡汤了求求了大神救救我，可以用温度设置条件，但是不能y用温度设置结果

**Comment by benshenhehe** [comment]
![1734193646253](https://github.com/user-attachments/assets/ce0148f8-415d-4fbf-9adb-f7d2f669110e)
![1734193670241](https://github.com/user-attachments/assets/1928681f-6c07-41d1-95a3-9f700938d019)

**Comment by benshenhehe** [comment]
就执行不能把空气能线控器设置到指定温度

**Comment by banto6** [comment]
请按issue模版提供设备信息

**Comment by benshenhehe** [comment]
> 请按issue模版提供设备信息

大神刚进这里没多久查了好久也不知道啥是issue模板，我把我能提供的信息全提供给您，您看看还缺什么

**Comment by benshenhehe** [comment]
@banto6 
![cf7c680e4d6fc90ef3dbeb7edd96838](https://github.com/user-attachments/assets/33500291-d81e-4a98-b16a-1446c2e39208)
![349fa1f3dbd2ef79e10fb60f6ac84d3](https://github.com/user-attachments/assets/3dba0b41-53e8-45c9-9c5d-b1b4d70de17c)
![d2d9fedd60682eb0856fe4b238ec698](https://github.com/user-attachments/assets/00c4ea94-531b-43f2-a9f8-27df145fa7e6)

**Comment by benshenhehe** [comment]
![Uploading 1734257809539.jpg…]()

**Comment by benshenhehe** [comment]
@
![1734257987043](https://github.com/user-attachments/assets/3dfcba0b-eb39-4c60-b7be-a0fcc1c827a1)

**Comment by benshenhehe** [comment]
![Uploading 68b11872737eef0075c15144a54a62f.png…]()

**Comment by benshenhehe** [comment]
![Uploading 1734257809539.jpg…]()

**Comment by benshenhehe** [comment]
![1734257809539](https://github.com/user-attachments/assets/89455247-1bdf-4316-9b92-02daec219bf0)

**Comment by benshenhehe** [comment]
![68b11872737eef0075c15144a54a62f](https://github.com/user-attachments/assets/b242140f-5645-435d-b54b-732e9e8dd636)

**Comment by benshenhehe** [comment]
看起来线控器只写了温度读取，没有写温度控制

**Comment by banto6** [comment]
模板参考： https://github.com/banto6/haier/issues/new?assignees=&labels=&projects=&template=%E6%8A%A5%E5%91%8A%E9%94%99%E8%AF%AF.md&title=

**Comment by benshenhehe** [comment]
**问题描述**
海尔空气能线控器，接入HA以后设置自动化，不能执行设定温度操作，举个例子，如果打开客厅灯，就执行海尔空气能线控器设置45度出水，这种自动化是执行不了的，因为在列表里没有这个选项，HA集成线控器拥有温度传感器，可以感知温度，但是不能设置。在海尔智家可以直接编写自动化，直接设置温度。
![68b11872737eef0075c15144a54a62f](https://github.com/user-attachments/assets/82729812-62e2-4380-9289-6febce89c5f8)


**环境信息:**
 - Homeassistant版本: [e.g. 2024.12.3]
![d78369b5f4f21fd7d09937ed591057b](https://github.com/user-attachments/assets/c4aa0d1a-7bcd-4f18-8b8d-e8929ea5987a)

**设备信息**
我不知道我找的设备信息对不对，请您指教。
![349fa1f3dbd2ef79e10fb60f6ac84d3](https://github.com/user-attachments/assets/0718b9a1-70a6-4563-bedc-2e3222e5922e)



**错误日志。

**Comment by benshenhehe** [comment]
访问7681端口，进入后输入login回车，文件在/mnt/data/supervisor/homeassistant/.storage/下，我已经在奋力学这个了，等我找到了我把设备信息补上。

**Comment by benshenhehe** [comment]
@banto6

**Comment by benshenhehe** [comment]
[device_5C241F645F5C空气能.json](https://github.com/user-attachments/files/18143928/device_5C241F645F5C.json)
这是设备信息 @banto6

**Comment by benshenhehe** [comment]
@banto6 我重新加载了下，不行 我又重启了下ha、还是不行，没有设定温度这个实体。拜托大神更新集成的时间写一个，跪下了

**Comment by banto6** [comment]
在设备开机的情况下重启/重载HA没有出现 《出水温度设定》这个实体？

**Comment by banto6** [comment]
用master分支代码再试试

**Comment by benshenhehe** [comment]
@banto6 大神可以远程连一下吗，可以付费，小白根本不会弄

**Comment by benshenhehe** [comment]
辛苦一个周了，就差这最后一步了，跪下了

**Comment by banto6** [comment]
在HACS更新成1.1.2试试吧，我单独发了一个版本

**Comment by benshenhehe** [comment]
成了大神，感谢 感谢
