### ISSUE TITLE
client ID和 refresh token无法认证登录

### ISSUE THREAD

**Issue by ttym** [banto6/haier#188]
**前言**
- 请自行搜索历史issues是否存在相同问题
- 尽量按格式填写Issues模版中的必要信息，没有这些信息就算提交了也解决不了任何问题。

**问题描述**
使用微信小程序 抓包的client ID和 refresh token无法认证登录，在windows环境与mac OS均试过

**环境信息:**
 - Homeassistant版本: [2024.12.04](https://www.home-assistant.io/blog/2024/12/04/release-202412/)

**设备信息**
无法登录

设备信息可在`.storage/haier/`目录下找到，文件格式为`device_设备ID.json`，上传文件时可将文件名和文件内容中的`设备ID`替换为任意值以保护个人隐私。

设备ID可开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。

**错误日志**
log里面仅有这一条关于haier模块的log，都是失败的，没有看到更详细的信息
120 2024-12-19 21:03:38.533 WARNING (MainThread) [custom_components.haier.config_flow] 接口返回异常: 授权异常或失败

**Comment by ttym** [comment]
<img width="381" alt="image" src="https://github.com/user-attachments/assets/d4a4a415-054c-43ff-9240-65686af965bb" />

此错误来自自定义集成。

日志记录器: custom_components.haier.config_flow
来源: custom_components/haier/config_flow.py:45
集成: Haier (文档, 问题)
首次出现: 22:00:43 (5 次总计出现)
上次记录: 22:11:23

接口返回异常: 授权异常或失败

**Comment by banto6** [comment]
我这边正常使用，等待其他用户报告，其他用户未报告则说明是client ID和 refresh token填写有误。

**Comment by ttym** [comment]
> 我这边正常使用，等待其他用户反馈，其他用户未反馈则说明是client ID和 refresh token填写有误。

我看[#176](https://github.com/banto6/haier/issues/176) 好像也是这个问题，但是日志信息里又看不出来具体是因为什么原因导致的无法认证，所以您这边看看是否知道是什么原因导致的无法认证登陆

**Comment by banto6** [comment]
我这边无法复现，截图看看你用的哪个接口里面的哪两个参数，参数值注意打码。

**Comment by ttym** [comment]
> 我这边无法复现，截图看看你用的哪个接口里面的哪两个参数，参数值注意打码。
这是我获取的小程序的token和client ID
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/7a8b2d7f-cdb4-4a39-94de-b217cf6bbcb8" />

**Comment by banto6** [comment]
接口错了，其他issues有教程，善用搜索

**Comment by ttym** [comment]
搞定了，根据抓包信息搜索关键字即可，这里大家注意一下 找到 ClientID 和 refreshToken  
https://zj.haier.net/api-gw/oauthserver/xxx 这类打头的api地址才是登录认证地址

**Comment by ttym** [comment]
搞定了，根据抓包信息搜索关键字即可，这里大家注意一下 找到 ClientID 和 refreshToken  
https://zj.haier.net/api-gw/oauthserver/xxx 这类打头的api地址才是登录认证地址

**Comment by baiduren** [comment]
我用app获取的 client id和refresh token ，不能登录，难道只是通过小程序获取吗
