### ISSUE TITLE
使用海尔智家账号登陆时认证失败

### ISSUE THREAD

**Issue by zhulongbaba** [banto6/haier#190]
**前言**
- 请自行搜索历史issues是否存在相同问题
- 尽量按格式填写Issues模版中的必要信息，没有这些信息就算提交了也解决不了任何问题。
使用海尔智家账号登陆时认证失败

**问题描述**
如题

**环境信息:**
 - Homeassistant版本: [e.g. 2023.6.2]
HAOS 13.2.1
**设备信息**
若是设备无法识别或控制错误则此项**必填**，没有设备信息可能会被直接关闭不做处理。

设备信息可在`.storage/haier/`目录下找到，文件格式为`device_设备ID.json`，上传文件时可将文件名和文件内容中的`设备ID`替换为任意值以保护个人隐私。

设备ID可开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。

![Uploading QQ截图20241225201704.png…]()

**错误日志**
若是运行报错或操控异常则日志**必填**，没有日志可能会被直接关闭不做处理。

日志记录器: custom_components.haier.config_flow
来源: custom_components/haier/config_flow.py:45
集成: Haier ([文档](https://github.com/banto6/haier), [问题](https://github.com/banto6/haier/issues))
首次出现: 20:21:43 (1 次总计出现)
上次记录: 20:21:43
接口返回异常: 授权异常或失败

**Comment by banto6** [comment]
检查clientId和token

**Comment by zhulongbaba** [comment]
我用小黄鸟刚抓到的还是认证失败，实在没招了

**Comment by zhulongbaba** [comment]
最后发现是token的问题，谢谢大佬
