### ISSUE TITLE
HSPK-X20UD海尔智能音箱，没有media_player实体，播放不了音乐。

### ISSUE THREAD

**Issue by SCDD21** [banto6/haier#192]
Core
2024.12.5
Supervisor
2024.12.0
Operating System
14.1
Frontend
20241127.8

haier集成版本1.1.2

设备：HSPK-X20UD海尔智能音箱

没有media_player实体，播放不了音乐。
另外关闭mic，关了就打不开，需要断电再插电。同样如果在ha里开了，再就再也关不了。也是断电再插电，应该是读取状态不对。

**Comment by banto6** [comment]
当前不支持media_player

**Comment by SCDD21** [comment]
有支持的计划吗？什么时候能支持

**Comment by banto6** [comment]
暂无计划，我没有此类设备，无法调试，欢迎PR
