### ISSUE TITLE
登陆认证失败

### ISSUE THREAD

**Issue by CharlesJxx** [banto6/haier#23]
**问题描述**
我昨天刚下载好插件也安装好了，在进入第一步登陆认证的时候出现认证失败这种信息，我确认过海尔智家的账号密码没有错误。

**Comment by banto6** [comment]
请提供一下错误日志

**Comment by bmzk00** [comment]
我也遇到了相同的问题，错误日志在哪里（已经开启了日志）

**Comment by CharlesJxx** [comment]
> 请提供一下错误日志

2023-07-22 19:28:04.343 WARNING (MainThread) [custom_components.haier.config_flow] bad_credentials

**Comment by CharlesJxx** [comment]
> > 请提供一下错误日志
> 
> 2023-07-22 19:28:04.343 WARNING (MainThread) [custom_components.haier.config_flow] bad_credentials

问题已经确认，手机上使用的账号密码登入ha不好用，我去官网重改了一下密码就好了

**Comment by banto6** [comment]
好的

**Comment by bmzk00** [comment]
> 

感谢！也通过这个方式解决了问题。不过卡萨帝的洗衣机和烘干机都没找到。
