### ISSUE TITLE
冰箱门状态识别错误，燃气热水器控制项异常，管线机控制项异常

### ISSUE THREAD

**Issue by qiaohewei** [banto6/haier#3]
<img width="322" alt="image" src="https://github.com/banto6/haier/assets/21193340/6a47cb01-e956-4e14-b30d-d2576a7f049f">

<img width="1069" alt="image" src="https://github.com/banto6/haier/assets/21193340/6da038d3-ec39-41c8-8dc5-6eb2fd6e59aa">

<img width="1131" alt="image" src="https://github.com/banto6/haier/assets/21193340/e124dff5-c9b1-40b7-88e7-ed1337bfafce">

很多项目是设备不支持的功能，不清楚为什么会显示。

**Comment by qiaohewei** [comment]
冰箱的速冻锁鲜和智能存储应该是相悖的条件，开启智能存储就不能开启速冻锁鲜，反之同理。

**Comment by banto6** [comment]
您好，目前项目还处于开发阶段，所以默认会展示获取到的所有字段，后期会加上字段过滤的功能

**Comment by banto6** [comment]
> 冰箱的速冻锁鲜和智能存储应该是相悖的条件，开启智能存储就不能开启速冻锁鲜，反之同理。

这个问题我等会加个log，你把log贴上来看看呢，目前是直接展示获取到的值，不应该会出现这种问题

**Comment by qiaohewei** [comment]
> 

方便的话留个联系方式，方便配合你完善该项目。

**Comment by banto6** [comment]
> > 
> 
> 方便的话留个联系方式，方便配合你完善该项目。

最好是在这里沟通吧，方便给后续遇到相同问题的兄弟一个参考。

**Comment by banto6** [comment]
> > 冰箱的速冻锁鲜和智能存储应该是相悖的条件，开启智能存储就不能开启速冻锁鲜，反之同理。
> 
> 这个问题我等会加个log，你把log贴上来看看呢，目前是直接展示获取到的值，不应该会出现这种问题

log已经加上了，可以拉一下最新代码运行导出一下日志

**Comment by qiaohewei** [comment]
[2023-06-29.log](https://github.com/banto6/haier/files/11906173/2023-06-29.log)

**Comment by qiaohewei** [comment]
冰箱
![1101688045566_ pic](https://github.com/banto6/haier/assets/21193340/2682ec7d-0bbd-4dce-996f-90acd38c62e1)

![image](https://github.com/banto6/haier/assets/21193340/0c85b7f6-cac6-4ee9-be0f-69ff5992a202)


开启智能存储时，冷藏、冷冻温度不可调整；软冻变温可以调整

开启速冻锁鲜时，冷藏、软冻变温可以调整；冷冻不可以调整

智能存储、速冻锁鲜均关闭时，全部可以调整

**Comment by banto6** [comment]
<img width="1196" alt="image" src="https://github.com/banto6/haier/assets/13196831/c2d32ce2-538c-4c6b-8999-954d4b85820b">

看数据冰箱门开关数据没有问题，页面上目前是显示什么状态呢；热水器和管线机控制项异常是指暂时出多余字段了吗？

**Comment by qiaohewei** [comment]
管线机
<img width="595" alt="image" src="https://github.com/banto6/haier/assets/21193340/32a86f8b-bfca-4141-8084-ccec04433955">

**Comment by qiaohewei** [comment]
燃气热水器
<img width="1106" alt="image" src="https://github.com/banto6/haier/assets/21193340/251d4363-4b0e-427b-96ea-b17d7cc4ff62">

**Comment by qiaohewei** [comment]
> <img alt="图像" width="1196" src="https://user-images.githubusercontent.com/13196831/249786506-c2d32ce2-538c-4c6b-8999-954d4b85820b.png">
> 看数据冰箱门开关数据没有问题，页面上目前显示什么状态呢；热水器和甲板机控制项异常是指暂时超出预留字段了吗？

这个冰箱APP 没有位置可以看到冰箱门开关状态。
<img width="325" alt="image" src="https://github.com/banto6/haier/assets/21193340/c7db7e4d-ef70-4d85-a7dd-f1b5a400c606">
我理解的是，我的门现在全是关着的，这个地方不应该显示关闭吗？

**Comment by banto6** [comment]
> > <img alt="图像" width="1196" src="https://user-images.githubusercontent.com/13196831/249786506-c2d32ce2-538c-4c6b-8999-954d4b85820b.png">
> > 看数据冰箱门开关数据没有问题，页面上目前显示什么状态呢；热水器和甲板机控制项异常是指暂时超出预留字段了吗？
> 
> 这个冰箱APP 没有位置可以看到冰箱门开关状态。 <img alt="image" width="325" src="https://user-images.githubusercontent.com/21193340/249788660-c7db7e4d-ef70-4d85-a7dd-f1b5a400c606.png"> 我理解的是，我的门现在全是关着的，这个地方不应该显示关闭吗？

冰箱门状态识别错误的问题已经修复了，可以用最新代码再试试；调温逻辑按我的理解hass应该实现不了吧，能否有案例参考？

**Comment by qiaohewei** [comment]
> > > <img alt="图像" width="1196" src="https://user-images.githubusercontent.com/13196831/249786506-c2d32ce2-538c-4c6b-8999-954d4b85820b.png">
> > > 看数据冰箱门开关数据没有问题，页面上目前显示什么状态呢；热水器和甲板机控制项异常是指暂时超出预留字段了吗？
> > 
> > 
> > 这个冰箱APP 没有位置可以看到冰箱门开关状态。 <img alt="image" width="325" src="https://user-images.githubusercontent.com/21193340/249788660-c7db7e4d-ef70-4d85-a7dd-f1b5a400c606.png"> 我理解的是，我的门现在全是关着的，这个地方不应该显示关闭吗？
> 
> 冰箱门状态识别错误的问题已经修复了，可以用最新代码再试试；调温逻辑按我的理解hass应该实现不了吧，能否有案例参考？
--------------------------------------------------------------------
我不确定是否能帮助到你
https://home-assistant-china.github.io/docs/scripts/conditions/
https://community.home-assistant.io/t/if-elif-else-with-no-else-what-do-you-do/70177/17

如果可以使用js的话，理论上可以使用一些逻辑判断，py,我完全不懂，所以这块难以提供帮助。

**Comment by banto6** [comment]
这貌似是自动化的语法，不确认能不能在component中使用；还有一个问题是目前项目是由拉取到的配置文件驱动，配置文件中没有描述此温控逻辑，要实现也只能根据设备类型和型号在代码中写死逻辑，这样不太方便后期维护
