### ISSUE TITLE
刚才更新了下，空调的climate实体没了

### ISSUE THREAD

**Issue by dwxiayi** [banto6/haier#30]
风管机，设备信息如下
Device Info: {'_raw_data': {'deviceId': '18A7F198C686', 'deviceName': '中央空调', 'deviceType': '0D012001', 'online': True, 'permissions': [{'auth': {'control': True, 'set': True, 'view': True}, 'authType': 'owner'}], 'productCodeT': 'AA9KK9007', 'productNameT': 'KFRD-72NW/64DDA21Z', 'totalPermission': {'control': True, 'set': True, 'view': True}, 'wifiType': '201c1200240008100d12f71c4094f300000080e384181627a2904f4940b24240'}}

另外设备的开关可以启动空调，但是climate面板无法启动空调。

**Comment by dwxiayi** [comment]
点climate的开关按钮空调有声音无法启停设备。

**Comment by dwxiayi** [comment]
设备[18A7F198C686]已获取到最新状态数据: {"silentSleepStatus": "false", "co2Value": "0", "intelligenceStatus": "false", "humidificationStatus": "false", "targetTemperature": "28.00", "vocValue": "0", "localFilterChangeFlag": "false", "energySavingStatus": "false", "electricHeatingStatus": "false", "freshAirStatus": "false", "ch2oValue": "0", "rapidMode": "false", "onOffStatus": "false", "windDirectionVertical": "0", "halfDegreeSettingStatus": "false", "echoStatus": "false", "outdoorTemperature": "29.00", "specialMode": "0", "10degreeHeatingStatus": "false", "pm2p5Level": "0", "ch2oCleaningStatus": "false", "humanSensingStatus": "0", "outdoorPM2p5Value": "0", "indoorPM2p5Value": "0", "acType": "0", "muteStatus": "false", "pmvStatus": "false", "healthMode": "false", "ErrAckFlag": "false", "pm2p5CleaningStatus": "false", "lightStatus": "false", "targetHumidity": "30", "totalCleaningTime": "0", "errCode": "", "sensingResult": "0", "tempUnit": "1", "lockStatus": "false", "selfCleaningStatus": "false", "indoorTemperature": "31.00", "windSpeed": "5", "airQuality": "0", "opSrc": "3", "screenDisplayStatus": "false", "operationMode": "1", "windDirectionHorizontal": "0", "indoorHumidity": "0"}

**Comment by banto6** [comment]
更新一下最新代码试试
