### ISSUE TITLE
请问大神能否将海尔空调的设定温度和模式控制做下改进呢？

### ISSUE THREAD

**Issue by 77215355** [banto6/haier#36]
首先非常感谢大神的付出，写出这个集成，已经解决了很大的问题，只是目前我个人使用下来，还是有些不是那么完美。请问大神能否将海尔空调的设定温度和模式做成面板类型的呢，目前这个用起来一大个版面， 在homeassistant里美观度远不如其他的集成，而且也不便于操作。另外是否有办法可以将设定温度和模式这些添加到巴法云里去操作呢。 再次感谢大神的工作！ 已经在github 关注。

**Comment by banto6** [comment]
master分支已新增Climate，如果还处于测试中，欢迎试用
