### ISSUE TITLE
洗衣机/洗护设备“提示信息”“洗涤阶段”传感器不可用

### ISSUE THREAD

**Issue by chenjiezb** [banto6/haier#40]
如题，更新了前几天的代码，发现海尔集成洗衣机设备下的“提示信息”“洗涤阶段”两个传感器变成“不可用”状态，不知道大侠能不能把这两个传感器恢复。对于我来说，这两个传感器提供的信息便于掌握设备运转过程，在自动化里采用相应代码给予提示或操作，比较实用。

**Comment by Necroneco** [comment]
更新下今天合并的那个提交，看看行不行

**Comment by chenjiezb** [comment]
测试结果报告，更新后上述传感器功能恢复，获取信息正常，感谢大佬们的辛勤付出！
