### ISSUE TITLE
在hass中配置，集成中没有haier，只有haier hon

### ISSUE THREAD

**Issue by jassonwang09** [banto6/haier#43]
在hass中配置，集成中没有haier，只有haier hon，请问我该如何安装集成呢，文件已经下载复制到本地了

**Comment by banto6** [comment]
尝试升级HA

**Comment by jassonwang09** [comment]
我看 ha 已经是最新版本了，2023.7.1 的版本

**Comment by banto6** [comment]
截图看看文件是怎么放的

**Comment by 13860605362** [comment]
可以添加自定义存储库，这样作者更新的时候hacs会提示，方便后期更新
