### ISSUE TITLE
海尔立式空调无法接入 型号：KFR-72L/GCB81U1室内机总成

### ISSUE THREAD

**Issue by jiejiefeiku** [banto6/haier#44]
家里有四台海尔空调，有三台挂式空调可以接入，但客厅的海尔立式空调无法接入，型号为：KFR-72L/GCB81U1室内机总成。
另外空调climate卡片温度显示有问题，目标温度设定只显示0-15度（实际对应16-31度），室内环境温度实际为27度时，climate卡片显示温度为54度，建议优化。

**Comment by jiejiefeiku** [comment]
![微信图片_20230730000704](https://github.com/banto6/haier/assets/126944788/ad388092-f16f-43a4-8dd6-0a7117f52ba6)
![微信截图_20230730000848](https://github.com/banto6/haier/assets/126944788/36514e24-f032-4366-ae0f-eb590ec9ae8f)

**Comment by banto6** [comment]
请使用最新代码根据issue模板反馈设备信息和日志信息

**Comment by jiejiefeiku** [comment]
[home-assistant_haier_2023-07-31T04-58-48.566Z.log](https://github.com/banto6/haier/files/12211614/home-assistant_haier_2023-07-31T04-58-48.566Z.log)
 是这样么？

**Comment by jiejiefeiku** [comment]
> 请使用最新代码根据issue模板反馈设备信息和日志信息
[home-assistant_haier_2023-07-31T04-58-48.566Z.log](https://github.com/banto6/haier/files/12211624/home-assistant_haier_2023-07-31T04-58-48.566Z.log)

是这样么？

**Comment by banto6** [comment]
1. 客厅的海尔立式空调无法接入

 see https://github.com/banto6/haier/issues/34

2. 温度显示问题

现在使用的最新master代码吗？我没在日志文件中找到设备信息，无法进一步排查

**Comment by jiejiefeiku** [comment]
> 1. 客厅的海尔立式空调接入点
> 
> 见#34
> 
> 2. 温度显示问题
> 
> 现在使用的最新主代码吗？我没有在日志文件中找到设备信息，无法进一步排查

[home-assistant_haier_2023-07-31T13-49-43.654Z.log](https://github.com/banto6/haier/files/12215725/home-assistant_haier_2023-07-31T13-49-43.654Z.log)
我打开调试日志后，在climate中操作了开关机和调节温度，看看这个日志里面有记录么？现在已经是使用最新的代码了。

**Comment by banto6** [comment]
设备信息需要集成重载后才会在日志显示，比如重启HA
