### ISSUE TITLE
卡萨帝冰箱温度传感器原始数据比实际数据大38

### ISSUE THREAD

**Issue by zhyf0610** [banto6/haier#45]
如图
![图片](https://github.com/banto6/haier/assets/42296671/f59bdc60-e8b6-4c1d-9fbc-4c8ce95b4f94)

**Comment by banto6** [comment]
请使用最新代码根据issue模板反馈设备信息和日志信息

**Comment by zhyf0610** [comment]
![IMG_20230730_201222](https://github.com/banto6/haier/assets/42296671/a84a10b1-3d33-4f4a-b152-048c3f0815d6)
![图片](https://github.com/banto6/haier/assets/42296671/7777d4cb-4991-4b48-bf90-f2b769a4b9a8)
![图片](https://github.com/banto6/haier/assets/42296671/246580ae-48d9-45bc-b664-857b53308397)
![图片](https://github.com/banto6/haier/assets/42296671/3ecab9d2-33f9-44f6-995b-e39e9ccc6dab)

**Comment by banto6** [comment]
您好，请使用最新代码根据issue模板反馈设备信息和日志信息，日志中需要包含一份该设备的状态数据以帮助问题定位

上图的数据对问题定位没有任何帮助

**Comment by zhyf0610** [comment]
设备信息：HAOS版本：10.3
HA  supervisor 版本：2023.07.1
HA Core 版本：2023.7.3

怀疑是海尔为了表示零下把所有数据加了38
