### ISSUE TITLE
海尔燃气热水器能否改成climate类型的？

### ISSUE THREAD

**Issue by pcj1997** [banto6/haier#46]
**问题描述**
目前燃气热水器有两个比较关键的实体：
1.开关机状态实体
switch.3429ef23bae1_onoffstatus
2.目标温度实体
number.3429ef23bae1_targettemp

开关机和调节温度都是通过这两个实体操作，是否能改成climate类型的实体，方便操作也方便桥接到HK里面。

**环境信息:**
 - Homeassistant版本: [e.g. 2023.7.2]

最后，感谢大佬对HA的贡献，让海尔设备的接入有了更多更好的选择！

**Comment by banto6** [comment]
您好，climate为空调实体，热水器不太合适映射到cliimate实体

**Comment by 77215355** [comment]
大佬6666，已经更新到最近的版本，实现了海尔空调的homekit，climate类型非常nice，不然先前的版本，一个空调满屏的按钮
