### ISSUE TITLE
海尔洗衣机 Warning-attribute airWashPara36 not found in the coordinator

### ISSUE THREAD

**Issue by sasukebinbin** [banto6/haier#47]
**问题描述**
海尔洗衣机
日志提示Warning

**环境信息:**
 - Homeassistant版本: 2023.6.1

此错误来自自定义集成。

Logger: custom_components.haier
Source: custom_components/haier/__init__.py:185
Integration: Haier (documentation, issues)
First occurred: 22:25:51 (74 occurrences)
Last logged: 22:25:51

Device A0822275C66A attribute airWashPara36 not found in the coordinator
Device A0822275C66A attribute airWashPara37 not found in the coordinator
Device A0822275C66A attribute airWashPara38 not found in the coordinator
Device A0822275C66A attribute airWashPara39 not found in the coordinator
Device A0822275C66A attribute airWashPara40 not found in the coordinator

**Comment by banto6** [comment]
正常情况
