### ISSUE TITLE
海尔空调无法控制

### ISSUE THREAD

**Issue by WnoteZZ** [banto6/haier#48]
**问题描述**
海尔空调无法控制

**环境信息:**
 - Homeassistant版本: [e.g. 2023.6.2]

**设备信息**
若是设备无法识别或控制错误则此项**必填**。
海尔  KFR-35GW/12CAA81U1

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

**错误日志**

**Comment by banto6** [comment]
无法控制是指？

**Comment by WnoteZZ** [comment]
1.比如我调节温度 会报错 日志我已经贴上了 
2.展示的数据不对 （温度等）

**Comment by banto6** [comment]
1.比如我调节温度 会报错 日志我已经贴上了

2.展示的数据不对 （温度等）

**Comment by WnoteZZ** [comment]
1、控制不了空调 选择风速、温度、扫风过几秒按钮会弹回 页面没有报错 
2、展示的温度数据和空调的温度不一样

**Comment by banto6** [comment]
<img width="844" alt="image" src="https://github.com/banto6/haier/assets/13196831/cd53f61e-6b7f-4029-9a27-30bfb58eafd3">
日志存在少量连接不了海尔服务器的错误，可以检查一下网络或重启HA后再试。

**Comment by WnoteZZ** [comment]
好的 谢谢大佬解惑
