### ISSUE TITLE
海尔空调的Climate (Beta)模块的疑问

### ISSUE THREAD

**Issue by 77215355** [banto6/haier#50]
Climate (Beta)海尔空调，每次通过语音启动海尔空调都是自动，现在是2023年8月，空调被设置成制热启动，是否可以可以修改一下，变成按照空调的上一次启动状态启动，就是打开开关机的，不进行调节，因为现在的海尔空调如果通过遥控器或者海尔app启动，都是能够按照上一次的状态运行，（温度，模式等等）。  我家用的是小米音响通过hasslife这个插件语音控制的

**Comment by 77215355** [comment]
我家用的是小米音响通过hasslife这个插件语音控制的，但是用语音控制，我的当前模式是 制冷的情况下 （例如：小爱同学温度设置为22度）就变成了制热22度，我的当前模式是 制冷，好奇怪，是什么问题导致会调节成制热模式，我看到在Climate (Beta里面有个自动选项，是这个原因吗

**Comment by banto6** [comment]
关于制热模式的问题可以看看在海尔智家APP和HA中显示的处于什么模式
1. 如果都显示是制热模式的话，那可能是小米音响语言控制的过程中出现了问题
2. 如果APP中显示制热，HA中显示制冷的话则可能是HA插件问题

**Comment by 77215355** [comment]
是通过小爱音箱语音调节温度的时候，就会变成制热模式，不管是降低温度还是升高温度

**Comment by Hsly404** [comment]
我也出现的这个问题

**Comment by 77215355** [comment]
HA中，和空调本体都是能正确指示，但是只要每次操作温度变更的控制都会出现这样的情况，不知道怎么回事

**Comment by 77215355** [comment]
现在的我的语音控制，就变成了：小爱同学，空调制冷 XX度， 而不能口语话表达：小爱同学，空调温度调高点/空调温度调低点，   或者空调温度XX度这样的词汇。  必须加上“制冷”这个控制关键词，不然就会被调整为制热 XX度了。 有没有可能是因为 在这个Climate里面，排列在最前的是 “自动”这个选项呢？

**Comment by banto6** [comment]
可以试试在HA中调整温度会不会复现，不复现的话建议先找小米音响插件的作者咨询这块的逻辑吧。
