### ISSUE TITLE
设置零冷水状态优化

### ISSUE THREAD

**Issue by zhu-cucu** [banto6/haier#52]
在设置燃气热水器 零冷水运行状态时候，只能设置更改为第一个选项，或者下一个选项，有没有可以自定义第几个选项，比如我只想要一个零冷水单次选项，目前实现办法只能是先select_first，再执行一次select_next，但如果我想选《零冷水运行状态》第五个选项，就得select_next5次，能不能直接由select_second ……这样的，或者直接再来一个选项框，选第几个参数

**Comment by banto6** [comment]
没明白你想表达的意思

**Comment by sclsj** [comment]
除了change [...] to first/last/previous/next option，还有 chage [...] option。选这个之后会有选项框可以选择一个选项。
