### ISSUE TITLE
海尔电热水器EC6002-D6(U1)没接入成功

### ISSUE THREAD

**Issue by lidicn** [banto6/haier#54]
**问题描述**
海尔电热水器EC6002-D6(U1) 没接入成功，没出现entity

**环境信息:**
 - Homeassistant版本: [e.g. 2023.6.2]

**设备信息**
若是设备无法识别或控制错误则此项**必填**。

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

**错误日志**

**Comment by lidicn** [comment]
Logger: custom_components.haier
Source: custom_components/haier/__init__.py:62
Integration: Haier ([documentation](https://github.com/banto6/haier), [issues](https://github.com/banto6/haier/issues))
First occurred: 2023年8月29日 23:58:37 (1 occurrences)
Last logged: 2023年8月29日 23:58:37

Device [DC330D2F5421] 未获取到可用attribute

**Comment by banto6** [comment]
see https://github.com/banto6/haier/issues/34
