### ISSUE TITLE
提交一个冰箱小bug

### ISSUE THREAD

**Issue by yyned2501** [banto6/haier#56]
**问题描述**
摄氏温度对应的华氏温度不正确

**环境信息:**
 - Homeassistant版本: 2023.8.4

**错误日志**
![image](https://github.com/banto6/haier/assets/43900325/d944aac9-ea22-49cd-af48-03a8fd104439)
![image](https://github.com/banto6/haier/assets/43900325/6dd20d37-bf6b-4ec7-bddd-47e29f084646)
![image](https://github.com/banto6/haier/assets/43900325/ac761af4-aa54-4f11-80dd-bf9dcdd2330a)

**Comment by banto6** [comment]
意思是文案不对吗？

**Comment by yyned2501** [comment]
嗯嗯 是的，比如冷藏室温度 摄氏4度 华氏应该是39.2度而不是35或51度。

**Comment by banto6** [comment]
文案是从海尔服务器获取的， 暂不支持修改
