### ISSUE TITLE
认证失败

### ISSUE THREAD

**Issue by Peterzhangnoise** [banto6/haier#58]
无论怎样输入账号密码，始终提示认证失败
![Screenshot_2023-09-12-21-43-08-930_com android chrome](https://github.com/banto6/haier/assets/70377914/681c79a5-1ccf-4b77-9ccb-f4757941593c)

**Comment by banto6** [comment]
或者参考 https://github.com/banto6/haier/issues/23#issuecomment-1646768109

**Comment by Peterzhangnoise** [comment]
已解决，去海尔官网忘记密码
