### ISSUE TITLE
账户认证失败

### ISSUE THREAD

**Issue by ininvi** [banto6/haier#60]
**问题描述**
配置海尔智家账户认证失败，已确认用户名及密码正确无误。

**环境信息:**
 Home Assistant 2023.9.3
Supervisor 2023.09.2
Operating System 10.4
前端版本： 20230911.0 - latest

**设备信息**
若是设备无法识别或控制错误则此项**必填**。

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
Logger: custom_components.haier.config_flow
Source: custom_components/haier/config_flow.py:33
Integration: Haier ([documentation](https://github.com/banto6/haier), [issues](https://github.com/banto6/haier/issues))
First occurred: 20:47:16 (3 occurrences)
Last logged: 20:58:16

bad_credentials
```

**错误日志**

**Comment by banto6** [comment]
see https://github.com/banto6/haier/issues/58
