### ISSUE TITLE
认证失败

### ISSUE THREAD

**Issue by doomlordcn** [banto6/haier#69]
**问题描述**
认证失败

**环境信息:**
 - Homeassistant版本: 2023.12.1

此错误来自自定义集成。

Logger: custom_components.haier.config_flow
Source: custom_components/haier/config_flow.py:33
Integration: Haier (documentation, issues)
First occurred: 23:08:31 (2 occurrences)
Last logged: 23:29:36

bad_credentials

**Comment by banto6** [comment]
see https://github.com/banto6/haier/issues/58
