### ISSUE TITLE
如何寻找说明文档

### ISSUE THREAD

**Issue by sclsj** [banto6/haier#73]
使用这个项目添加海尔热泵后，有249entities，很多不是顾名思义的。在哪里可以找到解释这些的说明文档？

**Comment by banto6** [comment]
entities是根据海尔云端的设备配置文件生成的，目前没有找到说明文档，所以暂时只能靠猜测使用。

**Comment by banto6** [comment]
意义不明的实体可以使用实体筛选功能删除

**Comment by sclsj** [comment]
这个项目（在较少更改后）可以作为独立程序使用吗？我有些想要创造的自动化需要计算数据，用python写更容易。如果可以的话有文档吗？

**Comment by banto6** [comment]
https://github.com/banto6/haier/blob/master/custom_components/haier/core/client.py

独立使用复制这一个文件即可

**Comment by sclsj** [comment]
这个文件好像import了其他文件，其他文件import了homeassistant
