### ISSUE TITLE
期待大神更新插件，让海尔智家更好用，谢谢

### ISSUE THREAD

**Issue by xionglei897** [banto6/haier#74]
期待大神更新插件，让海尔智家更好用，谢谢

**Comment by banto6** [comment]
目前暂时应该不会更新，原计划是切换为海尔智家APP的API以寻求更好的兼容性，但逆向遇到了一些阻碍，所以暂时搁置了

**Comment by xionglei897** [comment]
> 目前暂时应该不会更新，原计划是切换为海尔智家APP的API以寻求更好的兼容性，但逆向遇到了一些阻碍，所以暂时搁置了

好吧，但还是十分感谢你的奉献

**Comment by banto6** [comment]
可以后面留意一下，有抓到接口就会更新

**Comment by xionglei897** [comment]
> 可以后面留意一下，有抓到接口就会更新

好的，谢谢，我现在基本是三天一刷，看你有没有更新，再次谢谢你

**Comment by 13860605362** [comment]
> 目前暂时应该不会更新，原计划是切换为海尔智家APP的API以寻求更好的兼容性，但逆向遇到了一些阻碍，所以暂时搁置了

我有的设备在nodered的海尔插件能够获取信息，但是这个插件却获取不到。不知道是不是你说的api问题，期待插件的更新，也很感谢你的奉献

**Comment by banto6** [comment]
目前已切换为小程序API，可尝试使用最新版本
