### ISSUE TITLE
海尔智家中卡萨帝冰箱无法被搜多到

### ISSUE THREAD

**Issue by Liyi1998** [banto6/haier#76]
**问题描述**
海尔智家中有四个设备，洗衣机，干衣机，净水器，冰箱。冰箱无法被HA中hair集成扫描到，其余三个可以

**环境信息:**
 - Homeassistant版本: [e.g. 2023.12.4]

**设备信息**
BCD-647WLCTD79DYU1

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

**错误日志**

**Comment by banto6** [comment]
请提供日志

**Comment by Liyi1998** [comment]
此错误来自自定义集成。

Logger: custom_components.haier
Source: custom_components/haier/__init__.py:141
Integration: Haier (documentation, issues)
First occurred: 2023年12月31日 18:14:30 (3 occurrences)
Last logged: 2023年12月31日 21:02:54

Device [1457906FEB82] 未获取到可用attribute

**Comment by Liyi1998** [comment]
大佬你看上面是不，设备 id 可以对得上

**Comment by Liyi1998** [comment]
[home-assistant_2024-01-01T00-33-49.092Z.log](https://github.com/banto6/haier/files/13802464/home-assistant_2024-01-01T00-33-49.092Z.log)

**Comment by banto6** [comment]
<img width="1518" alt="image" src="https://github.com/banto6/haier/assets/13196831/db0340bc-424a-4001-b264-a0b373302f6f">

see https://github.com/banto6/haier/issues/34
