### ISSUE TITLE
海尔空调在插件内找不到

### ISSUE THREAD

**Issue by shanlanCoding** [banto6/haier#77]
**问题描述**
空调可以在海尔智家内看到并可以控制。但是在HA的haier插件内找不到设备实体。
![image](https://github.com/banto6/haier/assets/44717382/c7d04c26-a173-4b95-966c-48f65e225e5c)

**环境信息:**
 - Homeassistant版本: [e.g. 2023.6.2]
2023.12.0

**设备信息**
若是设备无法识别或控制错误则此项**必填**。
设备类型：挂式空调
设备型号：KFR-26GW/03JMY23AU1(Q)套机
设备编码：AA9WGW***
产品类别：智能

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

**错误日志**

**Comment by banto6** [comment]
请提供集成日志

**Comment by shanlanCoding** [comment]
> 请提供集成日志

[home-assistant_haier_2024-01-06T08-27-01.937Z.log](https://github.com/banto6/haier/files/13853037/home-assistant_haier_2024-01-06T08-27-01.937Z.log)

**Comment by banto6** [comment]
<img width="644" alt="image" src="https://github.com/banto6/haier/assets/13196831/4f0e8075-f1a7-4e57-a122-19e5571626d5">

see https://github.com/banto6/haier/issues/34
