### ISSUE TITLE
壁挂炉型号hj7,可以控制各种模式开关，但是无法调节温度

### ISSUE THREAD

**Issue by gm5ehh** [banto6/haier#81]
**问题描述**
壁挂炉型号hj7,可以控制各种模式开关，但是无法调节温度

**环境信息:**
 - Homeassistant版本: [e.g. 2023.6.2]

**设备信息**
海尔HJ7 26KW

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

**错误日志**

**Comment by banto6** [comment]
请提供一下调节温度后的日志信息
