### ISSUE TITLE
连接不上苹果手机怎么办

### ISSUE THREAD

**Issue by Breadovo** [banto6/haier#85]
**问题描述**

连不上homekit 一直显示未找到配件
**环境信息:**
 - Homeassistant版本: [e.g. 2023.6.2]

**设备信息**
若是设备无法识别或控制错误则此项**必填**。

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

**错误日志**

**Comment by banto6** [comment]
请具体描述

**Comment by Breadovo** [comment]
连接苹果homekit会一直转圈 后面会连接不上显示无此设备 KFR-35G/GCA81U1室内机总成这是空调型号

**Comment by banto6** [comment]
> 连接苹果homekit会一直转圈 后面会连接不上显示无此设备 KFR-35G/GCA81U1室内机总成这是空调型号

没太明白，方便录个操作视频么，还有就是设备在HA网页或APP上能不能正常使用？

**Comment by Breadovo** [comment]
录完视频怎么发出来

**Comment by Breadovo** [comment]
在ha网站上可以正常使用
就是连不上homekit

**Comment by Breadovo** [comment]
![image](https://github.com/banto6/haier/assets/157981760/f596e39f-3dc2-4b4b-b367-219855f80671)

**Comment by Breadovo** [comment]
![image](https://github.com/banto6/haier/assets/157981760/dd740e77-94a3-48f2-81a2-c0def1a45e76)![image](https://github.com/banto6/haier/assets/157981760/c6b0bbff-3bd1-4c7f-90b6-2bd2abd4e542)![image](https://github.com/banto6/haier/assets/157981760/59f1730f-bf13-488f-ad92-028ea7db53b1)![image](https://github.com/banto6/haier/assets/157981760/238d465d-0632-4d4c-869a-aaf46e57a21c)

**Comment by banto6** [comment]
个人经验这种一般是网络问题，可以尝试将HA与手机保持同一网段中试试
