### ISSUE TITLE
Appid与appkey验证失败

### ISSUE THREAD

**Issue by Seymourking** [banto6/haier#87]
**问题描述**
之前在ha里面直接使用没啥问题，今天用一个多键开关反复测试了十几次(每次按键间隔过短的话，海尔的设备没反应，需要大概15秒响应一次)之后，按键忽然失效，回到ha里面直接控制提示appid和appkey验证失败，请问这是触发类似风控了吗.......

**Comment by Seymourking** [comment]
删除账号重新添加也能显示设备，但依旧无法控制，海尔智家app里面可以控制

**Comment by woyaya** [comment]
今天遇到相同的问题
目前只能显示状态无法控制

**Comment by daisychainsaw00** [comment]
同样的问题，希望大佬可以解决

**Comment by ymj0424** [comment]
+1

**Comment by zhangguangjin** [comment]
我的刚刚也是这样

**Comment by reveever** [comment]
遇到了同样的问题

**Comment by leon4w** [comment]
+1

**Comment by otherbanana** [comment]
一样一样

**Comment by miloooliiii** [comment]
一样的情况，希望早日修复吧

**Comment by x10n9** [comment]
+1

**Comment by iapYang** [comment]
+1

**Comment by towerrush526** [comment]
+1

**Comment by huipeng2** [comment]
+1

**Comment by dalodi** [comment]
+1

**Comment by iapYang** [comment]
我看代码里appkey合appid都是写死的，猜测应该是作者在海尔智家平台写的某个应用，可能现在这个应用到期了

**Comment by ck003** [comment]
请问作者能把获取海尔智家平台的appkey和appid分享一下吗？

**Comment by launze** [comment]
现在临时换成node-red里面的海尔机器人了，这个还能用，期待作者更新

**Comment by dalodi** [comment]
> 现在临时换成node-red里面的海尔机器人了，这个还能用，期待作者更新

热水器还是不能用海尔机器人

**Comment by AkaJLock** [comment]
今天开始出现问题，希望作者大大跟进～

**Comment by fenglingR** [comment]
同状况，重载和重新登陆后可以查看状态，但无法控制

**Comment by banto6** [comment]
目前正在修复中

**Comment by jsgygujun** [comment]
+1，期待大佬的好消息

**Comment by rugal7699** [comment]
https://www.techweb.com.cn/world/2024-01-19/2939929.shtml
应该没事吧？

**Comment by Hugo7th** [comment]
碰到同样的问题，大佬加油！！等你的好消息。

**Comment by hsy5571615** [comment]
> > 现在临时换成node-red里面的海尔机器人了，这个还能用，期待作者更新
> 
> 热水器还是不能用海尔机器人

是啊，热水器没法控制，我家是空气能，用各种关键字试了都不行，洗衣机那些都OK，令人费解

**Comment by roy0319** [comment]
> > > 現在臨時換成海爾機器人裡面的node-red了，這個還能用期待，作者更新
> > 
> > 
> > 熱水器還是不能用海爾機器人
> 
> 是啊，熱水器無法控制，我家是空氣能，用各種關鍵字試了都不行，洗衣機那些都OK，令人費解

空氣能可以嘗試使用

打开热泵开关机状态
關閉热泵开关机状态

目前我使用是可行的

**Comment by hsy5571615** [comment]
> > > > 現在臨時換成海爾機器人裡面的node-red了，這個還能用期待，作者更新
> > > 
> > > 
> > > 熱水器還是不能用海爾機器人
> > 
> > 
> > 是啊，熱水器無法控制，我家是空氣能，用各種關鍵字試了都不行，洗衣機那些都OK，令人費解
> 
> 空氣能可以嘗試使用
> 
> 打开热泵开关机状态 關閉热泵开关机状态
> 
> 目前我使用是可行的

![微信截图_20240223143324](https://github.com/banto6/haier/assets/35516783/4e1d385f-f314-4e9d-a3b9-bed98a725374)
我好像还是不行，设备肯定是绑定过的

**Comment by banto6** [comment]
目前测试可以切换到微信小程序的APP_ID使用，但是因为登录token需要强绑定微信，所以后续将不支持账号密码登录，需要自行从微信小程序中抓取accessToken参数。

调整后的版本预计会在这两天更新

**Comment by banto6** [comment]
> 完全没问题，只是不知道 token 有效期有多长😂

目前计划单独做个Entity来提示token是否有效，无效了先手动更新。后续我会留意一下token的刷新机制

**Comment by x10n9** [comment]
我用苹果手机抓包海尔智家得到的APP_ID和APP_KEY，替换后热水器和冰箱恢复正常控制，不确定是否能共用和后续是否会失效

**Comment by rugal7699** [comment]
> 我用苹果手机抓包海尔智家app得到的APP_ID和APP_KEY，替换后热水器和冰箱恢复正常控制，不确定是否能共用和后续是否会失效

怎么抓包的呀，另外怎么替换呢？

**Comment by FMercurYG** [comment]
> > 我用苹果手机包海尔智家app获取的APP_ID和APP_KEY，更换后热水器和冰箱恢复正常控制，不确定是否能消费和后续是否会失效
> 
> 如果只是替换id和key的话应该是无法正常使用的，token也需要替换为APP端的token才行

刚测试，在client.py文件修改了APP_ID和APP_KEY，能正常使用

**Comment by banto6** [comment]
> > > 我用苹果手机抓包海尔智家app得到的APP_ID和APP_KEY，替换后热水器和冰箱恢复正常控制，不确定是否能共用和后续是否会失效
> > 
> > 
> > 如果只是替换id和key的话应该是无法正常使用的，token也需要替换为APP端的token才行
> 
> token不是动态获取的吗？我仅仅只是替换了id和key哦

我测试智家APP的ID和Key生成的token是无法正常使用，难道是我们的ID和KEY不一样？方便提供一下你抓取到的ID和Key吗？

**Comment by x10n9** [comment]
> > > > 我用苹果手机抓包海尔智家app得到的APP_ID和APP_KEY，替换后热水器和冰箱恢复正常控制，不确定是否能共用和后续是否会失效
> > > 
> > > 
> > > 如果只是替换id和key的话应该是无法正常使用的，token也需要替换为APP端的token才行
> > 
> > 
> > token不是动态获取的吗？我仅仅只是替换了id和key哦
> 
> 我测试智家APP的ID和Key生成的token是无法正常使用，难道是我们的ID和KEY不一样？方便提供一下你抓取到的ID和Key吗？



APP_ID = 'MB-UZHSH-0001'
APP_KEY = '5dfca8714eb26e3a776e58a8273c8752'

> > > > 我用苹果手机抓包海尔智家app得到的APP_ID和APP_KEY，替换后热水器和冰箱恢复正常控制，不确定是否能共用和后续是否会失效
> > > 
> > > 
> > > 如果只是替换id和key的话应该是无法正常使用的，token也需要替换为APP端的token才行
> > 
> > 
> > token不是动态获取的吗？我仅仅只是替换了id和key哦
> 
> 我测试智家APP的ID和Key生成的token是无法正常使用，难道是我们的ID和KEY不一样？方便提供一下你抓取到的ID和Key吗？
> 
> 额，我可能知道原因了，你应该没有去更新token，旧的token可能是通用的，你可以去HA中把`.storage/haier/手机号.token`文件删掉然后重启HA，看看登录会不会出现异常

刚操作试了，没有出现异常

APP_ID = 'MB-UZHSH-0001'
APP_KEY = '5dfca8714eb26e3a776e58a8273c8752'

> > > > 我用苹果手机抓包海尔智家app得到的APP_ID和APP_KEY，替换后热水器和冰箱恢复正常控制，不确定是否能共用和后续是否会失效
> > > 
> > > 
> > > 如果只是替换id和key的话应该是无法正常使用的，token也需要替换为APP端的token才行
> > 
> > 
> > token不是动态获取的吗？我仅仅只是替换了id和key哦
> 
> 我测试智家APP的ID和Key生成的token是无法正常使用，难道是我们的ID和KEY不一样？方便提供一下你抓取到的ID和Key吗？
> 
> 额，我可能知道原因了，你应该没有去更新token，旧的token可能是通用的，你可以去HA中把`.storage/haier/手机号.token`文件删掉然后重启HA，看看登录会不会出现异常

刚试了下，没有出现异常

APP_ID = 'MB-UZHSH-0001'
APP_KEY = '5dfca8714eb26e3a776e58a8273c8752'

**Comment by banto6** [comment]
@x10n9 我知道原因了，clientId和appId不是绑定的，我是因为替换了clientId才出现了问题。那可以先暂时修改APPID使用。考虑稳定性后续可能还是会调整为小程序的API

**Comment by FMercurYG** [comment]
> > > > > 我用苹果手机包海尔智家app获取的APP_ID和APP_KEY，更换后热水器和冰箱恢复正常控制，不确定是否能消费和后续是否会失效
> > > > 
> > > > 
> > > > 如果只是替换id和key的话应该是无法正常使用的，token也需要替换为APP端的token才行
> > > 
> > > 
> > > token不是动态获取的吗？我只需替换了id和key哦
> > 
> > 
> > 我测试智家APP的ID和Key生成的token无法正常使用，请问是我们的ID和KEY不一样吗？方便提供一下您抓取到的ID和Key吗？
> 
> APP_ID = 'MB-UZHSH-0001' APP_KEY = '5dfca8714eb26e3a776e58a8273c8752'
> 
> > > > > 我用苹果手机包海尔智家app获取的APP_ID和APP_KEY，更换后热水器和冰箱恢复正常控制，不确定是否能消费和后续是否会失效
> > > > 
> > > > 
> > > > 如果只是替换id和key的话应该是无法正常使用的，token也需要替换为APP端的token才行
> > > 
> > > 
> > > token不是动态获取的吗？我只需替换了id和key哦
> > 
> > 
> > 我测试智家APP的ID和Key生成的token无法正常使用，请问是我们的ID和KEY不一样吗？方便提供一下您抓取到的ID和Key吗？
> > 额，我可能知道原因了，你不应该去更新令牌，旧的令牌可能是通用的，你可以去HA中把`.storage/haier/手机号.token`文件删掉然后重新启动HA，看看登录会不会出现异常
> 
> 刚操作尝试了，没有出现异常
> 
> APP_ID = 'MB-UZHSH-0001' APP_KEY = '5dfca8714eb26e3a776e58a8273c8752'
> 
> > > > > 我用苹果手机包海尔智家app获取的APP_ID和APP_KEY，更换后热水器和冰箱恢复正常控制，不确定是否能消费和后续是否会失效
> > > > 
> > > > 
> > > > 如果只是替换id和key的话应该是无法正常使用的，token也需要替换为APP端的token才行
> > > 
> > > 
> > > token不是动态获取的吗？我只需替换了id和key哦
> > 
> > 
> > 我测试智家APP的ID和Key生成的token无法正常使用，请问是我们的ID和KEY不一样吗？方便提供一下您抓取到的ID和Key吗？
> > 额，我可能知道原因了，你不应该去更新令牌，旧的令牌可能是通用的，你可以去HA中把`.storage/haier/手机号.token`文件删掉然后重新启动HA，看看登录会不会出现异常
> 
> 刚试了下，没有出现异常
> 
> APP_ID = 'MB-UZHSH-0001' APP_KEY = '5dfca8714eb26e3a776e58a8273c8752'

相同的appid和key

**Comment by banto6** [comment]
各位，问题已修复，更新为最新版本即可。考虑稳定性后续可能还是会调整为小程序的API。

**Comment by x10n9** [comment]
> @x10n9 我知道原因了，clientId和appId不是绑定的，我是因为替换了clientId才出现了问题。那可以先暂时修改APPID使用。考虑稳定性后续可能还是会调整为小程序的API

了解，谢谢，想向您了解下原先用的的appid和appkey是安卓版抓取来的吗

**Comment by banto6** [comment]
> > @x10n9 我知道原因了，clientId和appId不是绑定的，我是因为替换了clientId才出现了问题。那可以先暂时修改APPID使用。考虑稳定性后续可能还是会调整为小程序的API
> 
> 了解，谢谢，想向您了解下原先用的的appid和appkey是安卓版抓取来的吗

不是，从另外一个APP逆向来的，不过现在已经找不到了，估计是下架了。

**Comment by qin-nz** [comment]
所以，现在有获取 clientid 和 token 的办法么？ 新用户完全不知道该咋搞
