### ISSUE TITLE
热水器无法控制了

### ISSUE THREAD

**Issue by zqdx41** [banto6/haier#88]
<img width="331" alt="Untitled" src="https://github.com/banto6/haier/assets/99741266/665833e8-6215-4b5f-adfd-833cf7b4370a">
**问题描述**
热水器无法控制了，报错如图，可能是因为热水器固件升级了？

**环境信息:**
 - Homeassistant版本: [e.g. 2023.6.2]

**设备信息**
若是设备无法识别或控制错误则此项**必填**。

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

**错误日志**

**Comment by banto6** [comment]
重复 https://github.com/banto6/haier/issues/87
