### ISSUE TITLE
卡萨帝热水器CEH-50LPLS5L(U1)，控制开关调整参数设置会提示以下内容

### ISSUE THREAD

**Issue by starguoyu** [banto6/haier#9]
卡萨帝热水器CEH-50LPLS5L(U1)
接收温度和开关状态没问题，控制开关调整参数设置会提示以下内容

调用服务 switch/turn_on 失败。 'DeviceCoordinator' object has no attribute 'device_id'

**Comment by banto6** [comment]
已修复，请拉取最新代码
