### ISSUE TITLE
是否无法支持零冷水热水器和洗烘套装

### ISSUE THREAD

**Issue by hzhuangdy** [banto6/haier#91]
**问题描述**
hacs安装了插件之后一个设备都搜不到。我用nodered的海尔机器人也说无法控制。是不是这几个设备不能用HA或者nodered插件了

**环境信息:**
 - Homeassistant版本: [e.g. 2023.6.2]

**设备信息**
若是设备无法识别或控制错误则此项**必填**。

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。
```
deviceType:
productCodeT:
productNameT:
wifiType:
```

**错误日志**

**Comment by banto6** [comment]
请提供集成日志

**Comment by hzhuangdy** [comment]
![image](https://github.com/banto6/haier/assets/36788357/ba165fe7-daa2-4fd9-9f21-c1dcd9e9d538)

**Comment by banto6** [comment]
可能是与当前设备无法兼容，暂时无解
