### ISSUE TITLE
再次询问关于设备支持的问题

### ISSUE THREAD

**Issue by roycho93** [banto6/haier#92]
**问题描述**

作者您好，非常感谢您的付出让大家能方便生活。
之前一个Issues中https://github.com/banto6/haier/issues/70
您说这个暂时无解，我后来又看到一个说法是如果海尔智家的微信小程序有的设备应该可以支持的，我现在的设备在小程序中可以看到，想请问是否HA有可能能支持呢？再次感谢。

**Comment by banto6** [comment]
后期会新增小程序的API，但目前还没有时间

**Comment by billcho2916603** [comment]
大佬，很感谢您开源这么好的项目
新版app用wss控制设备，配置文件是也在里面
如图：
![微信截图_20240324041712](https://github.com/banto6/haier/assets/73787244/9365d380-e0e3-43bd-b794-f46b2ecff5a1)

**Comment by billcho2916603** [comment]
data没有对称加密，我解密了一下，包含了attributes数据，和在您源码的键值有区别，其他一样 @banto6

**Comment by roycho93** [comment]
> 后期会新增小程序的API，但目前还没有时间

感谢回复，期待新增小程序API的更新!

**Comment by banto6** [comment]
目前已切换为小程序API，可尝试使用最新版本
