### ISSUE TITLE
冰箱传感器显示数据不正确

### ISSUE THREAD

**Issue by jkl8808** [banto6/haier#93]
冰箱型号：BCD-217WDVLU1

![image](https://github.com/banto6/haier/assets/140929290/da253290-b288-4c55-be9e-26914e98a61c)
如图

**Comment by banto6** [comment]
请提供集成debug级别日志

**Comment by jkl8808** [comment]
[home-assistant_haier_2024-03-08T10-44-17.947Z.log](https://github.com/banto6/haier/files/14537234/home-assistant_haier_2024-03-08T10-44-17.947Z.log)
是这个吗？

**Comment by banto6** [comment]
文件内没有DEBUG级别日志，检查一下日志等级设置

**Comment by jkl8808** [comment]
[home-assistant_haier_2024-03-08T12-08-33.884Z.log](https://github.com/banto6/haier/files/14538027/home-assistant_haier_2024-03-08T12-08-33.884Z.log)



2024-03-08 20:05:16.063 DEBUG (MainThread) [custom_components.haier.coordinator] 设备[04FA83E5B5E9]已获取到最新状态数据: {"refrigeratorDoorStatus": "false", "refrigeratorTargetTempLevel": "3", "freezerTemperatureC": "21", "freezerTargetTempLevel": "13", "quickFreezingMode": "false", "quickRefrigeratingMode": "false", "refrigeratorTemperatureC": "2", "showStatus": "false", "vtRoomTemperature": "31", "intelligenceMode": "false", "vtRoomTargetTempLevel": "24"

看起来是获取到的温度就是不对的，但是手机app的温度是对的（但是第一个"refirgertorTemperatureC"的数值也是对的）

**Comment by banto6** [comment]
这种应该是API本身的问题，后续等换成小程序的接口后可以再试试

**Comment by jkl8808** [comment]
好的好的，麻烦大佬了

**Comment by eduzhou** [comment]
这是显示温度就是设置温度的意思吗？不是冰箱实时温度

**Comment by jkl8808** [comment]
> 这是显示温度就是设置温度的意思吗？不是冰箱实时温度

这个传感器原本是应该显示实时温度的，如果显示设置温度那么冰箱也不至于能设置到30度😣

**Comment by eduzhou** [comment]
> > 这是显示温度就是设置温度的意思吗？不是冰箱实时温度
> 
> 这个传感器原本是应该显示实时温度的，如果显示设置温度那么冰箱也不至于能设置到30度😣

嗯，我有点迷惑，我在海尔智家里面只能看到两个温度，分别是冷藏冷冻的设置温度，看不到显示温度。添加了实体后增加了环境温湿度，不清楚是不是冰箱没有给实时温度，只给了设置温度。

**Comment by jkl8808** [comment]
> > > 这是显示温度就是设置温度的意思吗？不是冰箱实时温度
> > 
> > 
> > 这个传感器原本是应该显示实时温度的，如果显示设置温度那么冰箱也不至于能设置到30度😣
> 
> 嗯，我有点迷惑，我在海尔智家里面只能看到两个温度，分别是冷藏冷冻的设置温度，看不到显示温度。添加了实体后增加了环境温湿度，不清楚是不是冰箱没有给实时温度，只给了

**Comment by jkl8808** [comment]
> > > 这是显示温度就是设置温度的意思吗？不是冰箱实时温度
> > 
> > 
> > 这个传感器原本是应该显示实时温度的，如果显示设置温度那么冰箱也不至于能设置到30度😣
> 
> 嗯，我有点迷惑，我在海尔智家里面只能看到两个温度，分别是冷藏冷冻的设置温度，看不到显示温度。添加了实体后增加了环境温湿度，不清楚是不是冰箱没有给实时温度，只给了设置温度。

![IMG_20240314_132852](https://github.com/banto6/haier/assets/140929290/e2617a32-0eaa-4f97-b613-47124c65afe4)
我打圈那里应该是实时温度，然后加减号那里是设置温度

**Comment by eduzhou** [comment]
> > > > 这是显示温度就是设置温度的意思吗？不是冰箱实时温度
> > > 
> > > 
> > > 这个传感器原本是应该显示实时温度的，如果显示设置温度那么冰箱也不至于能设置到30度😣
> > 
> > 
> > 嗯，我有点迷惑，我在海尔智家里面只能看到两个温度，分别是冷藏冷冻的设置温度，看不到显示温度。添加了实体后增加了环境温湿度，不清楚是不是冰箱没有给实时温度，只给了设置温度。
> 
> ![IMG_20240314_132852](https://private-user-images.githubusercontent.com/140929290/312710599-e2617a32-0eaa-4f97-b613-47124c65afe4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzOTU1OTIsIm5iZiI6MTcxMDM5NTI5MiwicGF0aCI6Ii8xNDA5MjkyOTAvMzEyNzEwNTk5LWUyNjE3YTMyLTBlYWEtNGY5Ny1iNjEzLTQ3MTI0YzY1YWZlNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQwNTQ4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmM2ZjIzYjJmODRkNTJiZjdlNGU2OWYwODY2NDk1YjQ3ZDJlNjg1ODg1ZDBiMDU1ZWYxNjAxMzA5MGMzYWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lSwM8iLxGAhFvlhgsc-nyXfL85VQLad-P9CrXpbuS2g) 我打圈那里应该是实时温度，然后加减号那里是设置温度
![haier](https://github.com/banto6/haier/assets/118783404/9d01c130-3220-41f3-86f7-797d94a64761)
我的显示有，但是我估计它这个温度应该不准，我放了2个温度计，显示都冷藏在2度左右浮动。

**Comment by jkl8808** [comment]
> 目前已切换为小程序API，可尝试使用最新版本

wc太谢谢了，明天就去试试
