### ISSUE TITLE
海尔ZQD115F-E07JU1消毒柜控制异常

### ISSUE THREAD

**Issue by ykwac** [banto6/haier#94]
[home-assistant_2024-03-25T14-00-25.080Z.log](https://github.com/banto6/haier/files/14744712/home-assistant_2024-03-25T14-00-25.080Z.log)
大神辛苦啦，我在使用过程中还是碰到比较难懂的问题。
贴个图，这是集成里识别到的设备，可以控制开关，但是15秒左右会自动关闭设备。并且在功能模式中切换任何模式设备都不会相应。但是在手动切换消毒柜的消毒模式时，HA里的功能模式中可以看到模式的变化。总结来说就是可以显示设备状态但不能控制设备，这个是什么原因啊？
![图片1](https://github.com/banto6/haier/assets/13848236/79c0aec3-92f8-48c0-a678-dbae43057f63)

**Comment by banto6** [comment]
可以观察一下手动开启后有哪些实体状态发生了变化，可能除了切换模式还需要操作其他实体。
