### ISSUE TITLE
大佬！好像海尔又抽了？账号设置，认证失败

### ISSUE THREAD

**Issue by fangming828** [banto6/haier#97]
![WX20240428-215254@2x](https://github.com/banto6/haier/assets/87889242/d477135c-549f-415e-b79f-2c155d59c63b)
![WX20240428-215312@2x](https://github.com/banto6/haier/assets/87889242/bc3f5294-77cf-4765-9105-5801238f1b7e)

**Comment by banto6** [comment]
重复 https://github.com/banto6/haier/issues/98
