### ISSUE TITLE
登录海尔智家账户时报错，提示认证失败

### ISSUE THREAD

**Issue by Loyido** [banto6/haier#98]
**问题描述**
登录账号时，提示认证失败
确认账号密码是正确的

**环境信息:**
 - Homeassistant版本: [2023.12.4]

**设备信息**
none

以下信息开启debug模式后可在`Device Info`部分的日志中找到。日志可在`配置 > 系统 > 日志 > 加载完整日志`中查看。

**错误日志**

2024-04-28 13:52:24.304 WARNING (MainThread) [custom_components.haier.config_flow] uhome_token_request_error

**Comment by yduke** [comment]
俺也一样

**Comment by DaiLi-USTC** [comment]
同遇到这个问题

**Comment by hsy5571615** [comment]
同样遇到这个问题，有无临时解决办法呢？

**Comment by hsy5571615** [comment]
不得不感叹海尔总是搞些幺蛾子，别的品牌的HA插件很久都不用重新做适配

**Comment by Ciroygo** [comment]
牛逼，回家发现海尔设备掉线了，原来是海尔除妖蛾子了。

**Comment by suwen95** [comment]
有解决没？

**Comment by fangming828** [comment]
辛苦大佬！希望能解决！我也一样！

**Comment by qhdg23** [comment]
故障相同，求解决

**Comment by z4cki** [comment]
+1 蹲

**Comment by 248968499** [comment]
![image](https://github.com/banto6/haier/assets/22723404/bf88ec77-6fb7-4a9c-9bd3-5500d917601f)
这个获取token 的需要对接

**Comment by MapleEve** [comment]
UHOME的认证方式又变了。不知道海尔在玩什么

**Comment by mbdy20** [comment]
一样，等大佬修复

**Comment by 248968499** [comment]
有谁知道 ，海尔智家怎么 抓包吗？ 我用 fiddler 看不到 接口，

**Comment by zhyf0610** [comment]
海尔又搞什么灰机。。。大佬辛苦了

**Comment by dycwuxing** [comment]
原来大家都失败了...

**Comment by MapleEve** [comment]
> 有谁知道 ，海尔智家怎么 抓包吗？ 我用 fiddler 看不到 接口，

要用 MITM， surge可以抓到

**Comment by 248968499** [comment]
MITM 登录请求 抓不到，

**Comment by banto6** [comment]
51期间会修复，会调整改为小程序的API，由于接口限制，到时将不能使用账号密码登录，只能手动从小程序中抓取token使用

**Comment by dreamyuchen** [comment]
+1蹲

**Comment by MapleEve** [comment]
> 51期间会修复，会调整改为小程序的API，由于接口限制，到时将不能使用账号密码登录，只能手动从小程序中抓取token使用

和hon一样，名字改成fuck haier得了

**Comment by staritbusfans** [comment]
<img width="702" alt="IMG_4569" src="https://github.com/banto6/haier/assets/25558706/3000f114-5a9a-4123-8116-0294584f1cf3">
<img width="1170" alt="IMG_7295" src="https://github.com/banto6/haier/assets/25558706/ab27e11f-215c-4ef1-9417-7d0ba856ac8d">
开 放 联 盟

**Comment by ERRORCODE6** [comment]
一样的问题，坐等更新了，希望尽快能解决😜

**Comment by sxx1314** [comment]
> 不能使用账号密码登录，只

小程序好像有的空调只能走蓝牙控制  app里却又能wifi控制  神一样的逻辑

**Comment by LiuYaKu** [comment]
小程序支持的设备太少了，我的设备里只有净水器在小程序里面🥹

**Comment by LiuYaKu** [comment]
空调和洗碗机都不在里面

**Comment by LiuYaKu** [comment]
我的空调和洗碗机都不在小程序里面😭

**Comment by Kyle0820** [comment]
> [v1.0.0-alpha](https://github.com/banto6/haier/releases/tag/v1.0.0-alpha) 已发布，后续有问题请新开issue

大佬，看你的说明要自己抓包拿token了……以后岂不是每次token过期都得手动拿一遍token啊……
